package tui

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/lipgloss"

	"github.com/trentas/ptop/pkg/collector"
)

// siCodeKernel is si_code SI_KERNEL — the signal was generated by the kernel
// (a fault, a timer, a pipe close), not sent by another process.
const siCodeKernel = 0x80

// signalMessage renders a SignalEvent as a one-line "name ← origin" for the F7
// timeline. A kernel-generated signal (SI_KERNEL) is attributed to the kernel;
// otherwise it names the sending process (pid + comm).
func signalMessage(e collector.SignalEvent) string {
	if e.Code == siCodeKernel {
		return fmt.Sprintf("%s (kernel)", e.Signal)
	}
	if e.SenderComm != "" {
		return fmt.Sprintf("%s ← pid %d (%s)", e.Signal, e.SenderPID, e.SenderComm)
	}
	return fmt.Sprintf("%s ← pid %d", e.Signal, e.SenderPID)
}

// procLifecycleMessage renders a ProcLifecycleEvent as a one-line entry for the
// F7 timeline: "fork → pid (comm)", "exec /path (pid)", or "exit pid (comm)".
func procLifecycleMessage(e collector.ProcLifecycleEvent) string {
	switch e.Kind {
	case "fork":
		return fmt.Sprintf("fork → pid %d (%s) ← pid %d", e.PID, e.Comm, e.PPID)
	case "exec":
		if e.Filename != "" {
			return fmt.Sprintf("exec %s (pid %d)", e.Filename, e.PID)
		}
		return fmt.Sprintf("exec (pid %d, %s)", e.PID, e.Comm)
	case "exit":
		return fmt.Sprintf("exit pid %d (%s)", e.PID, e.Comm)
	default:
		return fmt.Sprintf("%s pid %d (%s)", e.Kind, e.PID, e.Comm)
	}
}

// securityMessage renders a SecurityEvent as a one-line entry for the F7
// timeline. exec-map → "mmap rwx anon @0x… (func)" with W^X/anon called out;
// lsm-decision → the detail summary.
func securityMessage(e collector.SecurityEvent) string {
	if e.Kind == "lsm-decision" {
		return "lsm: " + e.Detail
	}
	tags := ""
	if e.WriteExec {
		tags += " W^X"
	}
	if e.Anon {
		tags += " anon"
	}
	site := securityCallSiteLabel(e)
	if site != "" {
		site = " " + site
	}
	return fmt.Sprintf("%s %s%s @0x%x%s", e.Op, protBits(e.Prot), tags, e.Addr, site)
}

// securityCallSiteLabel renders the symbolized originating call site, preferring
// "func (file:line)" → "func" → "module+0xoffset" → the raw hex / "unknown".
func securityCallSiteLabel(e collector.SecurityEvent) string {
	switch {
	case e.Func != "" && e.File != "":
		return fmt.Sprintf("%s (%s:%d)", e.Func, e.File, e.Line)
	case e.Func != "":
		return e.Func
	case e.Module != "":
		return fmt.Sprintf("%s+0x%x", e.Module, e.Offset)
	case e.AddrHex != "":
		return e.AddrHex
	default:
		return ""
	}
}

// protBits renders a PROT_* bitmask as rwx (mirrors the collector's protString,
// kept here so the TUI doesn't reach into the collector's unexported helper).
func protBits(prot uint32) string {
	b := []byte("---")
	if prot&0x1 != 0 {
		b[0] = 'r'
	}
	if prot&0x2 != 0 {
		b[1] = 'w'
	}
	if prot&0x4 != 0 {
		b[2] = 'x'
	}
	return string(b)
}

// renderTimelineView (F7) — assets/mockup.jsx → TimelineView
// Stream completo de eventos com badge por categoria.
func renderTimelineView(m Model, w, h int) string {
	if w < 30 || h < 6 {
		return MutedStyle.Render("(terminal pequeno demais)")
	}
	body := renderTimelineFull(m.Timeline, w-2, h-3)
	return Panel("Full Event Stream", body, w, h)
}

func renderTimelineFull(events []collector.TimelineEvent, w, h int) string {
	if h <= 0 {
		return ""
	}
	visible := events
	if len(visible) > h {
		visible = visible[:h]
	}
	const tsW = 12
	const catW = 5
	msgW := w - tsW - catW - 2
	if msgW < 8 {
		msgW = 8
	}

	lines := make([]string, 0, len(visible))
	for _, e := range visible {
		ts := lipgloss.NewStyle().Foreground(ColorDim).Background(ColorPanel).Width(tsW).
			Render(e.Timestamp.Format("15:04:05.000"))
		c := CategoryColor(e.Category)
		cat := lipgloss.NewStyle().
			Foreground(c).
			Background(ColorPanel).
			Width(catW).
			Align(lipgloss.Center).
			Render(strings.TrimSpace(CategoryLabel(e.Category)))
		msg := lipgloss.NewStyle().Foreground(ColorText).Background(ColorPanel).Width(msgW).
			Render(truncate(e.Message, msgW))
		lines = append(lines, panelRow(ts, cat, msg))

	}
	return strings.Join(lines, "\n")
}
