// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: event.proto

package streampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category mirrors the F7 Timeline taxonomy. Every Event carries one so a
// consumer can filter without inspecting the payload oneof.
type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_CATEGORY_CPU         Category = 1
	Category_CATEGORY_SYSCALL     Category = 2
	Category_CATEGORY_NETWORK     Category = 3
	Category_CATEGORY_MEMORY      Category = 4
	Category_CATEGORY_THREAD      Category = 5
	Category_CATEGORY_IO          Category = 6
	Category_CATEGORY_FD          Category = 7
	Category_CATEGORY_LOCK        Category = 8
	Category_CATEGORY_TIMELINE    Category = 9
	Category_CATEGORY_SIGNAL      Category = 10 // #58 — signals delivered to the target
	Category_CATEGORY_PROCESS     Category = 11 // #60 — execution context + exec lineage
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0:  "CATEGORY_UNSPECIFIED",
		1:  "CATEGORY_CPU",
		2:  "CATEGORY_SYSCALL",
		3:  "CATEGORY_NETWORK",
		4:  "CATEGORY_MEMORY",
		5:  "CATEGORY_THREAD",
		6:  "CATEGORY_IO",
		7:  "CATEGORY_FD",
		8:  "CATEGORY_LOCK",
		9:  "CATEGORY_TIMELINE",
		10: "CATEGORY_SIGNAL",
		11: "CATEGORY_PROCESS",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_CPU":         1,
		"CATEGORY_SYSCALL":     2,
		"CATEGORY_NETWORK":     3,
		"CATEGORY_MEMORY":      4,
		"CATEGORY_THREAD":      5,
		"CATEGORY_IO":          6,
		"CATEGORY_FD":          7,
		"CATEGORY_LOCK":        8,
		"CATEGORY_TIMELINE":    9,
		"CATEGORY_SIGNAL":      10,
		"CATEGORY_PROCESS":     11,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_event_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_event_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

// StackRef references a stack captured at event time and resolved out-of-band
// (#54 — stack symbolization). stack_id is the kernel stack-map id; build_id is
// the target executable's GNU build-id, a stable per-process cache key (the
// same stack_id means a different stack once the binary changes). Consumers
// fetch the frames via EventStreamService.ResolveStack.
type StackRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StackId       uint64                 `protobuf:"varint,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	BuildId       string                 `protobuf:"bytes,2,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackRef) Reset() {
	*x = StackRef{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackRef) ProtoMessage() {}

func (x *StackRef) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackRef.ProtoReflect.Descriptor instead.
func (*StackRef) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *StackRef) GetStackId() uint64 {
	if x != nil {
		return x.StackId
	}
	return 0
}

func (x *StackRef) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// StackFrame is one symbolized frame of a captured stack (#54), leaf-first.
// func is "" when the address couldn't be resolved to a function (stripped
// non-Go module — module+offset still locate it); file/line are populated only
// for Go modules in this cut (C/C++ file:line needs DWARF). offset is
// module-relative, so it is comparable across runs/ASLR.
type StackFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Func          string                 `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Module        string                 `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	Offset        uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	BuildId       string                 `protobuf:"bytes,6,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StackFrame) Reset() {
	*x = StackFrame{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StackFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StackFrame) ProtoMessage() {}

func (x *StackFrame) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StackFrame.ProtoReflect.Descriptor instead.
func (*StackFrame) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *StackFrame) GetFunc() string {
	if x != nil {
		return x.Func
	}
	return ""
}

func (x *StackFrame) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *StackFrame) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *StackFrame) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *StackFrame) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StackFrame) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// Event is the single unified message on the stream. The envelope carries the
// common fields (time, pid/tid, category, optional stack); the category-
// specific data lives in the payload oneof. Snapshot-style payloads (lists)
// represent full current state, not deltas — the same semantics the in-process
// collector channels use today.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wall-clock capture time in Unix nanoseconds (from the collector's
	// time.Time). Per-payload timestamps collapse onto this envelope field.
	TsUnixNano int64 `protobuf:"varint,1,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	Pid        int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// tid is 0 when the event is not thread-scoped (most snapshots).
	Tid      int32    `protobuf:"varint,3,opt,name=tid,proto3" json:"tid,omitempty"`
	Category Category `protobuf:"varint,4,opt,name=category,proto3,enum=ptop.v1.Category" json:"category,omitempty"`
	// Optional; unset until #54.
	Stack *StackRef `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	// Execution-context identity stamped on EVERY event (#60). uid/gid are the
	// target's real user/group; cgroup_id is the inode of its cgroup directory
	// (== bpf_get_current_cgroup_id() on cgroup v2). All three are 0 until the
	// first ProcContext snapshot has been observed, and on platforms without
	// /proc (macOS). The rich strings (cgroup path, container id, namespace
	// inodes) live in the periodic ProcContext payload, not on every envelope.
	Uid      uint32 `protobuf:"varint,6,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid      uint32 `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	CgroupId uint64 `protobuf:"varint,8,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Cpu
	//	*Event_Syscalls
	//	*Event_Network
	//	*Event_Memory
	//	*Event_Threads
	//	*Event_IoWait
	//	*Event_IoThroughput
	//	*Event_Io
	//	*Event_Fds
	//	*Event_FdEvent
	//	*Event_Locks
	//	*Event_Timeline
	//	*Event_Heap
	//	*Event_HeapEvent
	//	*Event_NetError
	//	*Event_FsEvent
	//	*Event_Signal
	//	*Event_Tls
	//	*Event_ProcContext
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

func (x *Event) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Event) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *Event) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *Event) GetStack() *StackRef {
	if x != nil {
		return x.Stack
	}
	return nil
}

func (x *Event) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Event) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Event) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetCpu() *CpuSample {
	if x != nil {
		if x, ok := x.Payload.(*Event_Cpu); ok {
			return x.Cpu
		}
	}
	return nil
}

func (x *Event) GetSyscalls() *SyscallSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Syscalls); ok {
			return x.Syscalls
		}
	}
	return nil
}

func (x *Event) GetNetwork() *NetworkSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Network); ok {
			return x.Network
		}
	}
	return nil
}

func (x *Event) GetMemory() *MemStats {
	if x != nil {
		if x, ok := x.Payload.(*Event_Memory); ok {
			return x.Memory
		}
	}
	return nil
}

func (x *Event) GetThreads() *ThreadSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Threads); ok {
			return x.Threads
		}
	}
	return nil
}

func (x *Event) GetIoWait() *IoWaitSample {
	if x != nil {
		if x, ok := x.Payload.(*Event_IoWait); ok {
			return x.IoWait
		}
	}
	return nil
}

func (x *Event) GetIoThroughput() *IoThroughputSample {
	if x != nil {
		if x, ok := x.Payload.(*Event_IoThroughput); ok {
			return x.IoThroughput
		}
	}
	return nil
}

func (x *Event) GetIo() *IoSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Io); ok {
			return x.Io
		}
	}
	return nil
}

func (x *Event) GetFds() *FdSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Fds); ok {
			return x.Fds
		}
	}
	return nil
}

func (x *Event) GetFdEvent() *FdEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_FdEvent); ok {
			return x.FdEvent
		}
	}
	return nil
}

func (x *Event) GetLocks() *LockSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Locks); ok {
			return x.Locks
		}
	}
	return nil
}

func (x *Event) GetTimeline() *TimelineEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Timeline); ok {
			return x.Timeline
		}
	}
	return nil
}

func (x *Event) GetHeap() *HeapSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*Event_Heap); ok {
			return x.Heap
		}
	}
	return nil
}

func (x *Event) GetHeapEvent() *HeapEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_HeapEvent); ok {
			return x.HeapEvent
		}
	}
	return nil
}

func (x *Event) GetNetError() *NetErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_NetError); ok {
			return x.NetError
		}
	}
	return nil
}

func (x *Event) GetFsEvent() *FSEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_FsEvent); ok {
			return x.FsEvent
		}
	}
	return nil
}

func (x *Event) GetSignal() *SignalEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *Event) GetTls() *TLSPayloadEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Tls); ok {
			return x.Tls
		}
	}
	return nil
}

func (x *Event) GetProcContext() *ProcContext {
	if x != nil {
		if x, ok := x.Payload.(*Event_ProcContext); ok {
			return x.ProcContext
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Cpu struct {
	Cpu *CpuSample `protobuf:"bytes,10,opt,name=cpu,proto3,oneof"`
}

type Event_Syscalls struct {
	Syscalls *SyscallSnapshot `protobuf:"bytes,11,opt,name=syscalls,proto3,oneof"`
}

type Event_Network struct {
	Network *NetworkSnapshot `protobuf:"bytes,12,opt,name=network,proto3,oneof"`
}

type Event_Memory struct {
	Memory *MemStats `protobuf:"bytes,13,opt,name=memory,proto3,oneof"`
}

type Event_Threads struct {
	Threads *ThreadSnapshot `protobuf:"bytes,14,opt,name=threads,proto3,oneof"`
}

type Event_IoWait struct {
	IoWait *IoWaitSample `protobuf:"bytes,15,opt,name=io_wait,json=ioWait,proto3,oneof"`
}

type Event_IoThroughput struct {
	IoThroughput *IoThroughputSample `protobuf:"bytes,16,opt,name=io_throughput,json=ioThroughput,proto3,oneof"`
}

type Event_Io struct {
	Io *IoSnapshot `protobuf:"bytes,17,opt,name=io,proto3,oneof"`
}

type Event_Fds struct {
	Fds *FdSnapshot `protobuf:"bytes,18,opt,name=fds,proto3,oneof"`
}

type Event_FdEvent struct {
	FdEvent *FdEvent `protobuf:"bytes,19,opt,name=fd_event,json=fdEvent,proto3,oneof"`
}

type Event_Locks struct {
	Locks *LockSnapshot `protobuf:"bytes,20,opt,name=locks,proto3,oneof"`
}

type Event_Timeline struct {
	Timeline *TimelineEvent `protobuf:"bytes,21,opt,name=timeline,proto3,oneof"`
}

type Event_Heap struct {
	// #52 capabilities:
	Heap *HeapSnapshot `protobuf:"bytes,22,opt,name=heap,proto3,oneof"` // #53 — periodic heap aggregate
}

type Event_HeapEvent struct {
	HeapEvent *HeapEvent `protobuf:"bytes,23,opt,name=heap_event,json=heapEvent,proto3,oneof"` // #53 — per alloc/free
}

type Event_NetError struct {
	NetError *NetErrorEvent `protobuf:"bytes,24,opt,name=net_error,json=netError,proto3,oneof"` // #56 — detailed network error
}

type Event_FsEvent struct {
	FsEvent *FSEvent `protobuf:"bytes,25,opt,name=fs_event,json=fsEvent,proto3,oneof"` // #57 — filesystem semantics (denial/delete/rename)
}

type Event_Signal struct {
	Signal *SignalEvent `protobuf:"bytes,26,opt,name=signal,proto3,oneof"` // #58 — signal delivered to the target, with origin
}

type Event_Tls struct {
	Tls *TLSPayloadEvent `protobuf:"bytes,27,opt,name=tls,proto3,oneof"` // #55 — pre-encryption / post-decryption plaintext
}

type Event_ProcContext struct {
	ProcContext *ProcContext `protobuf:"bytes,28,opt,name=proc_context,json=procContext,proto3,oneof"` // #60 — periodic namespace/cgroup/identity snapshot
}

func (*Event_Cpu) isEvent_Payload() {}

func (*Event_Syscalls) isEvent_Payload() {}

func (*Event_Network) isEvent_Payload() {}

func (*Event_Memory) isEvent_Payload() {}

func (*Event_Threads) isEvent_Payload() {}

func (*Event_IoWait) isEvent_Payload() {}

func (*Event_IoThroughput) isEvent_Payload() {}

func (*Event_Io) isEvent_Payload() {}

func (*Event_Fds) isEvent_Payload() {}

func (*Event_FdEvent) isEvent_Payload() {}

func (*Event_Locks) isEvent_Payload() {}

func (*Event_Timeline) isEvent_Payload() {}

func (*Event_Heap) isEvent_Payload() {}

func (*Event_HeapEvent) isEvent_Payload() {}

func (*Event_NetError) isEvent_Payload() {}

func (*Event_FsEvent) isEvent_Payload() {}

func (*Event_Signal) isEvent_Payload() {}

func (*Event_Tls) isEvent_Payload() {}

func (*Event_ProcContext) isEvent_Payload() {}

// ─── CPU ──────────────────────────────────────────────────────────────────
type CpuSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsagePct      float64                `protobuf:"fixed64,1,opt,name=usage_pct,json=usagePct,proto3" json:"usage_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpuSample) Reset() {
	*x = CpuSample{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpuSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpuSample) ProtoMessage() {}

func (x *CpuSample) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpuSample.ProtoReflect.Descriptor instead.
func (*CpuSample) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *CpuSample) GetUsagePct() float64 {
	if x != nil {
		return x.UsagePct
	}
	return 0
}

// ─── Syscalls ───────────────────────────────────────────────────────────────
type SyscallStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LatencyNs     uint64                 `protobuf:"varint,3,opt,name=latency_ns,json=latencyNs,proto3" json:"latency_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallStat) Reset() {
	*x = SyscallStat{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallStat) ProtoMessage() {}

func (x *SyscallStat) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallStat.ProtoReflect.Descriptor instead.
func (*SyscallStat) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *SyscallStat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyscallStat) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SyscallStat) GetLatencyNs() uint64 {
	if x != nil {
		return x.LatencyNs
	}
	return 0
}

type SyscallSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*SyscallStat         `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallSnapshot) Reset() {
	*x = SyscallSnapshot{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallSnapshot) ProtoMessage() {}

func (x *SyscallSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallSnapshot.ProtoReflect.Descriptor instead.
func (*SyscallSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *SyscallSnapshot) GetStats() []*SyscallStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

// ─── Network ────────────────────────────────────────────────────────────────
type NetConn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "TCP" | "UDP" | "UNIX"
	Remote        string                 `protobuf:"bytes,3,opt,name=remote,proto3" json:"remote,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // "ESTABLISHED" | "WAIT" | "RECV" | "LISTEN"
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`     // "→" | "←" | "↔"
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,7,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,8,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetConn) Reset() {
	*x = NetConn{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetConn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetConn) ProtoMessage() {}

func (x *NetConn) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetConn.ProtoReflect.Descriptor instead.
func (*NetConn) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *NetConn) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *NetConn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NetConn) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *NetConn) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NetConn) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *NetConn) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *NetConn) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetConn) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

type NetworkSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conns         []*NetConn             `protobuf:"bytes,1,rep,name=conns,proto3" json:"conns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkSnapshot) Reset() {
	*x = NetworkSnapshot{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSnapshot) ProtoMessage() {}

func (x *NetworkSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSnapshot.ProtoReflect.Descriptor instead.
func (*NetworkSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkSnapshot) GetConns() []*NetConn {
	if x != nil {
		return x.Conns
	}
	return nil
}

// NetErrorEvent is a kernel-observed network failure (#56), correlated to a
// connection by its peer 5-tuple. kind is "refused" (RST while still
// connecting), "reset" (RST mid-stream), or "retransmit" (a tcp_retransmit_skb
// fired). detail_ms is the latency from the relevant baseline to the RST
// (SYN_SENT→RST for refused, ESTABLISHED→RST for reset); 0 for retransmit.
// retransmits is the connection's running retransmit count at event time. The
// event timestamp lives on the Event envelope.
type NetErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Remote        string                 `protobuf:"bytes,2,opt,name=remote,proto3" json:"remote,omitempty"` // peer host:port
	Retransmits   uint32                 `protobuf:"varint,3,opt,name=retransmits,proto3" json:"retransmits,omitempty"`
	DetailMs      float64                `protobuf:"fixed64,4,opt,name=detail_ms,json=detailMs,proto3" json:"detail_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetErrorEvent) Reset() {
	*x = NetErrorEvent{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetErrorEvent) ProtoMessage() {}

func (x *NetErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetErrorEvent.ProtoReflect.Descriptor instead.
func (*NetErrorEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

func (x *NetErrorEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NetErrorEvent) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *NetErrorEvent) GetRetransmits() uint32 {
	if x != nil {
		return x.Retransmits
	}
	return 0
}

func (x *NetErrorEvent) GetDetailMs() float64 {
	if x != nil {
		return x.DetailMs
	}
	return 0
}

// TLSPayloadEvent is plaintext observed around a TLS call (#55), captured via
// libssl uprobes before encryption (dir "write") or after decryption (dir
// "read"). fd is the owning socket (−1 if unknown); len is the call's plaintext
// byte count. data holds up to the configured cap of those bytes and is EMPTY
// unless --tls-bytes was set (metadata-only default). Category on the envelope
// is NETWORK; the event timestamp lives on the envelope.
//
// PRIVACY: data may contain credentials/PII. Capture is opt-in (--tls) and the
// payload bytes require the additional --tls-bytes flag. Consumers of the stream
// must treat data as sensitive.
type TLSPayloadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           string                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"` // "write" | "read"
	Fd            int32                  `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Len           int32                  `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"` // captured plaintext (≤ cap; empty in metadata-only mode)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSPayloadEvent) Reset() {
	*x = TLSPayloadEvent{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSPayloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSPayloadEvent) ProtoMessage() {}

func (x *TLSPayloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSPayloadEvent.ProtoReflect.Descriptor instead.
func (*TLSPayloadEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *TLSPayloadEvent) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *TLSPayloadEvent) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *TLSPayloadEvent) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *TLSPayloadEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ─── Memory ─────────────────────────────────────────────────────────────────
type MemStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RssBytes      uint64                 `protobuf:"varint,1,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	HeapBytes     uint64                 `protobuf:"varint,2,opt,name=heap_bytes,json=heapBytes,proto3" json:"heap_bytes,omitempty"`
	PageFaults    uint64                 `protobuf:"varint,3,opt,name=page_faults,json=pageFaults,proto3" json:"page_faults,omitempty"`
	AllocsPerS    uint64                 `protobuf:"varint,4,opt,name=allocs_per_s,json=allocsPerS,proto3" json:"allocs_per_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemStats) Reset() {
	*x = MemStats{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemStats) ProtoMessage() {}

func (x *MemStats) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemStats.ProtoReflect.Descriptor instead.
func (*MemStats) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

func (x *MemStats) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *MemStats) GetHeapBytes() uint64 {
	if x != nil {
		return x.HeapBytes
	}
	return 0
}

func (x *MemStats) GetPageFaults() uint64 {
	if x != nil {
		return x.PageFaults
	}
	return 0
}

func (x *MemStats) GetAllocsPerS() uint64 {
	if x != nil {
		return x.AllocsPerS
	}
	return 0
}

// ─── Heap allocations (#53 — libc malloc/free pairing) ──────────────────────
// HeapEvent is a single allocation or free observed via libc uprobes. op is
// "malloc"|"calloc"|"realloc"|"free"; lifetime_ms is set on free; call_site is
// the application call-site address (resolved to a symbol out-of-band by #54).
type HeapEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Addr          uint64                 `protobuf:"varint,3,opt,name=addr,proto3" json:"addr,omitempty"`
	LifetimeMs    float64                `protobuf:"fixed64,4,opt,name=lifetime_ms,json=lifetimeMs,proto3" json:"lifetime_ms,omitempty"`
	CallSite      uint64                 `protobuf:"varint,5,opt,name=call_site,json=callSite,proto3" json:"call_site,omitempty"`
	Large         bool                   `protobuf:"varint,6,opt,name=large,proto3" json:"large,omitempty"` // allocation ≥ 128KB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapEvent) Reset() {
	*x = HeapEvent{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapEvent) ProtoMessage() {}

func (x *HeapEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapEvent.ProtoReflect.Descriptor instead.
func (*HeapEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *HeapEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *HeapEvent) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *HeapEvent) GetAddr() uint64 {
	if x != nil {
		return x.Addr
	}
	return 0
}

func (x *HeapEvent) GetLifetimeMs() float64 {
	if x != nil {
		return x.LifetimeMs
	}
	return 0
}

func (x *HeapEvent) GetCallSite() uint64 {
	if x != nil {
		return x.CallSite
	}
	return 0
}

func (x *HeapEvent) GetLarge() bool {
	if x != nil {
		return x.Large
	}
	return false
}

// HeapCallSite aggregates the live allocations attributed to one application
// call site (by the alloc site, so a free decrements where it was allocated).
//
// call_site is the raw instruction pointer; func/file/line/module/offset are its
// symbolization (#54). func is "" when the address can't be resolved to a
// function (stripped non-Go module — module+offset still locate it); file/line
// are set only for Go modules in this cut (C/C++ file:line needs DWARF). addr_hex
// is the raw-address fallback ("0x…", or "unknown" when the stack walk failed).
type HeapCallSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallSite      uint64                 `protobuf:"varint,1,opt,name=call_site,json=callSite,proto3" json:"call_site,omitempty"`
	AddrHex       string                 `protobuf:"bytes,2,opt,name=addr_hex,json=addrHex,proto3" json:"addr_hex,omitempty"` // raw-address fallback ("0x…"; "unknown" when unresolved)
	LiveBytes     uint64                 `protobuf:"varint,3,opt,name=live_bytes,json=liveBytes,proto3" json:"live_bytes,omitempty"`
	AllocCount    uint64                 `protobuf:"varint,4,opt,name=alloc_count,json=allocCount,proto3" json:"alloc_count,omitempty"`
	AvgLifetimeMs float64                `protobuf:"fixed64,5,opt,name=avg_lifetime_ms,json=avgLifetimeMs,proto3" json:"avg_lifetime_ms,omitempty"`
	Suspected     bool                   `protobuf:"varint,6,opt,name=suspected,proto3" json:"suspected,omitempty"` // has live allocations older than the leak threshold
	Func          string                 `protobuf:"bytes,7,opt,name=func,proto3" json:"func,omitempty"`            // resolved function name ("" if unresolved)
	File          string                 `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`            // source file (Go only in this cut; "" otherwise)
	Line          int32                  `protobuf:"varint,9,opt,name=line,proto3" json:"line,omitempty"`           // source line (0 if unknown)
	Module        string                 `protobuf:"bytes,10,opt,name=module,proto3" json:"module,omitempty"`       // backing module basename ("" if unresolved)
	Offset        uint64                 `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`      // module-relative offset of the call site
	// Kernel stack-map id of the alloc site, for EventStreamService.ResolveStack
	// (the full leaf-first stack). A sentinel (resolves to not-found) when the
	// stack walk failed.
	StackId       uint64 `protobuf:"varint,12,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeapCallSite) Reset() {
	*x = HeapCallSite{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapCallSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapCallSite) ProtoMessage() {}

func (x *HeapCallSite) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapCallSite.ProtoReflect.Descriptor instead.
func (*HeapCallSite) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

func (x *HeapCallSite) GetCallSite() uint64 {
	if x != nil {
		return x.CallSite
	}
	return 0
}

func (x *HeapCallSite) GetAddrHex() string {
	if x != nil {
		return x.AddrHex
	}
	return ""
}

func (x *HeapCallSite) GetLiveBytes() uint64 {
	if x != nil {
		return x.LiveBytes
	}
	return 0
}

func (x *HeapCallSite) GetAllocCount() uint64 {
	if x != nil {
		return x.AllocCount
	}
	return 0
}

func (x *HeapCallSite) GetAvgLifetimeMs() float64 {
	if x != nil {
		return x.AvgLifetimeMs
	}
	return 0
}

func (x *HeapCallSite) GetSuspected() bool {
	if x != nil {
		return x.Suspected
	}
	return false
}

func (x *HeapCallSite) GetFunc() string {
	if x != nil {
		return x.Func
	}
	return ""
}

func (x *HeapCallSite) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *HeapCallSite) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *HeapCallSite) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *HeapCallSite) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *HeapCallSite) GetStackId() uint64 {
	if x != nil {
		return x.StackId
	}
	return 0
}

// HeapSnapshot is the periodic heap aggregate. live_heap_bytes and
// suspected_leak_bytes derive from the kernel's LRU-bounded live set, so they
// undercount on alloc-heavy targets — never exact. alloc_rate is allocations
// per second over the last window.
type HeapSnapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LiveHeapBytes      uint64                 `protobuf:"varint,1,opt,name=live_heap_bytes,json=liveHeapBytes,proto3" json:"live_heap_bytes,omitempty"`
	AllocRate          float64                `protobuf:"fixed64,2,opt,name=alloc_rate,json=allocRate,proto3" json:"alloc_rate,omitempty"`
	SuspectedLeakBytes uint64                 `protobuf:"varint,3,opt,name=suspected_leak_bytes,json=suspectedLeakBytes,proto3" json:"suspected_leak_bytes,omitempty"`
	TopCallSites       []*HeapCallSite        `protobuf:"bytes,4,rep,name=top_call_sites,json=topCallSites,proto3" json:"top_call_sites,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeapSnapshot) Reset() {
	*x = HeapSnapshot{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeapSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeapSnapshot) ProtoMessage() {}

func (x *HeapSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeapSnapshot.ProtoReflect.Descriptor instead.
func (*HeapSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *HeapSnapshot) GetLiveHeapBytes() uint64 {
	if x != nil {
		return x.LiveHeapBytes
	}
	return 0
}

func (x *HeapSnapshot) GetAllocRate() float64 {
	if x != nil {
		return x.AllocRate
	}
	return 0
}

func (x *HeapSnapshot) GetSuspectedLeakBytes() uint64 {
	if x != nil {
		return x.SuspectedLeakBytes
	}
	return 0
}

func (x *HeapSnapshot) GetTopCallSites() []*HeapCallSite {
	if x != nil {
		return x.TopCallSites
	}
	return nil
}

// ─── Threads ────────────────────────────────────────────────────────────────
type ThreadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tid           int32                  `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // "running" | "blocked" | "sleeping"
	CpuPct        float64                `protobuf:"fixed64,4,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	Waiting       string                 `protobuf:"bytes,5,opt,name=waiting,proto3" json:"waiting,omitempty"`                             // blocking lock/syscall name, empty if none
	CtxSwitches   uint64                 `protobuf:"varint,6,opt,name=ctx_switches,json=ctxSwitches,proto3" json:"ctx_switches,omitempty"` // eBPF-only; 0 via /proc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadInfo) Reset() {
	*x = ThreadInfo{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadInfo) ProtoMessage() {}

func (x *ThreadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadInfo.ProtoReflect.Descriptor instead.
func (*ThreadInfo) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *ThreadInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ThreadInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ThreadInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ThreadInfo) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *ThreadInfo) GetWaiting() string {
	if x != nil {
		return x.Waiting
	}
	return ""
}

func (x *ThreadInfo) GetCtxSwitches() uint64 {
	if x != nil {
		return x.CtxSwitches
	}
	return 0
}

type ThreadSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*ThreadInfo          `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadSnapshot) Reset() {
	*x = ThreadSnapshot{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadSnapshot) ProtoMessage() {}

func (x *ThreadSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadSnapshot.ProtoReflect.Descriptor instead.
func (*ThreadSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *ThreadSnapshot) GetThreads() []*ThreadInfo {
	if x != nil {
		return x.Threads
	}
	return nil
}

// ─── I/O ──────────────────────────────────────────────────────────────────
type IoWaitSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pct           float64                `protobuf:"fixed64,1,opt,name=pct,proto3" json:"pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoWaitSample) Reset() {
	*x = IoWaitSample{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoWaitSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoWaitSample) ProtoMessage() {}

func (x *IoWaitSample) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoWaitSample.ProtoReflect.Descriptor instead.
func (*IoWaitSample) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *IoWaitSample) GetPct() float64 {
	if x != nil {
		return x.Pct
	}
	return 0
}

type IoThroughputSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReadBytesPerS  float64                `protobuf:"fixed64,1,opt,name=read_bytes_per_s,json=readBytesPerS,proto3" json:"read_bytes_per_s,omitempty"`
	WriteBytesPerS float64                `protobuf:"fixed64,2,opt,name=write_bytes_per_s,json=writeBytesPerS,proto3" json:"write_bytes_per_s,omitempty"`
	ReadOps        uint64                 `protobuf:"varint,3,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`    // cumulative since process start
	WriteOps       uint64                 `protobuf:"varint,4,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"` // cumulative
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IoThroughputSample) Reset() {
	*x = IoThroughputSample{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoThroughputSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoThroughputSample) ProtoMessage() {}

func (x *IoThroughputSample) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoThroughputSample.ProtoReflect.Descriptor instead.
func (*IoThroughputSample) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *IoThroughputSample) GetReadBytesPerS() float64 {
	if x != nil {
		return x.ReadBytesPerS
	}
	return 0
}

func (x *IoThroughputSample) GetWriteBytesPerS() float64 {
	if x != nil {
		return x.WriteBytesPerS
	}
	return 0
}

func (x *IoThroughputSample) GetReadOps() uint64 {
	if x != nil {
		return x.ReadOps
	}
	return 0
}

func (x *IoThroughputSample) GetWriteOps() uint64 {
	if x != nil {
		return x.WriteOps
	}
	return 0
}

type IoFileStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "db" | "log" | "cfg" | "tmp" | "proc"
	Reads         uint64                 `protobuf:"varint,3,opt,name=reads,proto3" json:"reads,omitempty"`
	Writes        uint64                 `protobuf:"varint,4,opt,name=writes,proto3" json:"writes,omitempty"`
	Bytes         uint64                 `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Fsyncs        uint64                 `protobuf:"varint,7,opt,name=fsyncs,proto3" json:"fsyncs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IoFileStats) Reset() {
	*x = IoFileStats{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoFileStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoFileStats) ProtoMessage() {}

func (x *IoFileStats) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoFileStats.ProtoReflect.Descriptor instead.
func (*IoFileStats) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *IoFileStats) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IoFileStats) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IoFileStats) GetReads() uint64 {
	if x != nil {
		return x.Reads
	}
	return 0
}

func (x *IoFileStats) GetWrites() uint64 {
	if x != nil {
		return x.Writes
	}
	return 0
}

func (x *IoFileStats) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *IoFileStats) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *IoFileStats) GetFsyncs() uint64 {
	if x != nil {
		return x.Fsyncs
	}
	return 0
}

type LatencyBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Read          float64                `protobuf:"fixed64,2,opt,name=read,proto3" json:"read,omitempty"`
	Write         float64                `protobuf:"fixed64,3,opt,name=write,proto3" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyBucket) Reset() {
	*x = LatencyBucket{}
	mi := &file_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyBucket) ProtoMessage() {}

func (x *LatencyBucket) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyBucket.ProtoReflect.Descriptor instead.
func (*LatencyBucket) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{19}
}

func (x *LatencyBucket) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LatencyBucket) GetRead() float64 {
	if x != nil {
		return x.Read
	}
	return 0
}

func (x *LatencyBucket) GetWrite() float64 {
	if x != nil {
		return x.Write
	}
	return 0
}

type IoSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReadBytesPerS  float64                `protobuf:"fixed64,1,opt,name=read_bytes_per_s,json=readBytesPerS,proto3" json:"read_bytes_per_s,omitempty"`
	WriteBytesPerS float64                `protobuf:"fixed64,2,opt,name=write_bytes_per_s,json=writeBytesPerS,proto3" json:"write_bytes_per_s,omitempty"`
	ReadOps        uint64                 `protobuf:"varint,3,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`
	WriteOps       uint64                 `protobuf:"varint,4,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"`
	Fsyncs         uint64                 `protobuf:"varint,5,opt,name=fsyncs,proto3" json:"fsyncs,omitempty"`
	Opens          uint64                 `protobuf:"varint,6,opt,name=opens,proto3" json:"opens,omitempty"`
	IoWaitPct      float64                `protobuf:"fixed64,7,opt,name=io_wait_pct,json=ioWaitPct,proto3" json:"io_wait_pct,omitempty"`
	TopFiles       []*IoFileStats         `protobuf:"bytes,8,rep,name=top_files,json=topFiles,proto3" json:"top_files,omitempty"`
	LatencyBuckets []*LatencyBucket       `protobuf:"bytes,9,rep,name=latency_buckets,json=latencyBuckets,proto3" json:"latency_buckets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IoSnapshot) Reset() {
	*x = IoSnapshot{}
	mi := &file_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IoSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IoSnapshot) ProtoMessage() {}

func (x *IoSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IoSnapshot.ProtoReflect.Descriptor instead.
func (*IoSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{20}
}

func (x *IoSnapshot) GetReadBytesPerS() float64 {
	if x != nil {
		return x.ReadBytesPerS
	}
	return 0
}

func (x *IoSnapshot) GetWriteBytesPerS() float64 {
	if x != nil {
		return x.WriteBytesPerS
	}
	return 0
}

func (x *IoSnapshot) GetReadOps() uint64 {
	if x != nil {
		return x.ReadOps
	}
	return 0
}

func (x *IoSnapshot) GetWriteOps() uint64 {
	if x != nil {
		return x.WriteOps
	}
	return 0
}

func (x *IoSnapshot) GetFsyncs() uint64 {
	if x != nil {
		return x.Fsyncs
	}
	return 0
}

func (x *IoSnapshot) GetOpens() uint64 {
	if x != nil {
		return x.Opens
	}
	return 0
}

func (x *IoSnapshot) GetIoWaitPct() float64 {
	if x != nil {
		return x.IoWaitPct
	}
	return 0
}

func (x *IoSnapshot) GetTopFiles() []*IoFileStats {
	if x != nil {
		return x.TopFiles
	}
	return nil
}

func (x *IoSnapshot) GetLatencyBuckets() []*LatencyBucket {
	if x != nil {
		return x.LatencyBuckets
	}
	return nil
}

// ─── Filesystem semantics (#57) ─────────────────────────────────────────────
// FSEvent is a kernel-observed filesystem semantic event: a permission denial on
// open/openat (op="denied", err EACCES/EPERM), a delete (op="deleted"), or a
// rename (op="renamed"). new_path is the rename destination ("" otherwise);
// errno/err carry the syscall result (0/"" on success — deletes and renames are
// emitted on success too, denials only on failure). Category on the envelope is
// IO; the event timestamp lives on the envelope.
type FSEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"` // "denied" | "deleted" | "renamed"
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	NewPath       string                 `protobuf:"bytes,3,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"` // rename destination; "" otherwise
	Errno         int32                  `protobuf:"varint,4,opt,name=errno,proto3" json:"errno,omitempty"`                   // 0 on success; positive errno (EACCES=13, …)
	Err           string                 `protobuf:"bytes,5,opt,name=err,proto3" json:"err,omitempty"`                        // "EACCES" | "EPERM" | "ENOENT" | "" …
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSEvent) Reset() {
	*x = FSEvent{}
	mi := &file_event_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSEvent) ProtoMessage() {}

func (x *FSEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSEvent.ProtoReflect.Descriptor instead.
func (*FSEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{21}
}

func (x *FSEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *FSEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FSEvent) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *FSEvent) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *FSEvent) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// ─── Signals (#58) ──────────────────────────────────────────────────────────
// SignalEvent is a signal delivered to the target, captured at kernel generation
// time — including who sent it. signal is the symbolic name ("SIGPIPE");
// sender_pid/sender_comm identify the sending process (for kernel-generated
// signals like SIGSEGV the sender is the target itself); target_tid is the
// receiving thread. code is si_code (SI_USER/SI_KERNEL/…) — a root-cause hint;
// result is the kernel TRACE_SIGNAL_* disposition. Category on the envelope is
// SIGNAL; the event timestamp lives on the envelope.
type SignalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        string                 `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"` // "SIGPIPE", "SIGTERM", … (or "SIG<n>")
	Signo         int32                  `protobuf:"varint,2,opt,name=signo,proto3" json:"signo,omitempty"`
	SenderPid     int32                  `protobuf:"varint,3,opt,name=sender_pid,json=senderPid,proto3" json:"sender_pid,omitempty"`
	SenderComm    string                 `protobuf:"bytes,4,opt,name=sender_comm,json=senderComm,proto3" json:"sender_comm,omitempty"`
	TargetTid     int32                  `protobuf:"varint,5,opt,name=target_tid,json=targetTid,proto3" json:"target_tid,omitempty"`
	Code          int32                  `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`     // si_code
	Result        int32                  `protobuf:"varint,7,opt,name=result,proto3" json:"result,omitempty"` // TRACE_SIGNAL_* disposition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalEvent) Reset() {
	*x = SignalEvent{}
	mi := &file_event_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEvent) ProtoMessage() {}

func (x *SignalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEvent.ProtoReflect.Descriptor instead.
func (*SignalEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{22}
}

func (x *SignalEvent) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *SignalEvent) GetSigno() int32 {
	if x != nil {
		return x.Signo
	}
	return 0
}

func (x *SignalEvent) GetSenderPid() int32 {
	if x != nil {
		return x.SenderPid
	}
	return 0
}

func (x *SignalEvent) GetSenderComm() string {
	if x != nil {
		return x.SenderComm
	}
	return ""
}

func (x *SignalEvent) GetTargetTid() int32 {
	if x != nil {
		return x.TargetTid
	}
	return 0
}

func (x *SignalEvent) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SignalEvent) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// ─── Execution context (#60) ────────────────────────────────────────────────
// ProcContext is the target's container/execution context, read from /proc and
// emitted periodically (and once at start). uid/gid are the real user/group;
// the *_ns fields are the inode numbers of the target's namespaces (from
// /proc/<pid>/ns/*) — equal across processes in the same namespace, so they
// identify container/sandbox membership. cgroup_id is the inode of the cgroup
// directory (matches bpf_get_current_cgroup_id() on cgroup v2); cgroup is its
// path. container is a best-effort id derived from the cgroup path
// ("docker:<12hex>", "containerd:…", "kubepods:…", "libpod:…", "lxc:…"), or ""
// when the target isn't in a recognized container. Category on the envelope is
// PROCESS; the snapshot time lives on the envelope. This payload is Linux-only
// (namespaces/cgroups don't exist on macOS).
type ProcContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,2,opt,name=gid,proto3" json:"gid,omitempty"`
	PidNs         uint64                 `protobuf:"varint,3,opt,name=pid_ns,json=pidNs,proto3" json:"pid_ns,omitempty"`
	NetNs         uint64                 `protobuf:"varint,4,opt,name=net_ns,json=netNs,proto3" json:"net_ns,omitempty"`
	MntNs         uint64                 `protobuf:"varint,5,opt,name=mnt_ns,json=mntNs,proto3" json:"mnt_ns,omitempty"`
	UserNs        uint64                 `protobuf:"varint,6,opt,name=user_ns,json=userNs,proto3" json:"user_ns,omitempty"`
	CgroupNs      uint64                 `protobuf:"varint,7,opt,name=cgroup_ns,json=cgroupNs,proto3" json:"cgroup_ns,omitempty"`
	IpcNs         uint64                 `protobuf:"varint,8,opt,name=ipc_ns,json=ipcNs,proto3" json:"ipc_ns,omitempty"`
	UtsNs         uint64                 `protobuf:"varint,9,opt,name=uts_ns,json=utsNs,proto3" json:"uts_ns,omitempty"`
	CgroupId      uint64                 `protobuf:"varint,10,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	Cgroup        string                 `protobuf:"bytes,11,opt,name=cgroup,proto3" json:"cgroup,omitempty"`       // cgroup path (v2 "0::/p" → "/p")
	Container     string                 `protobuf:"bytes,12,opt,name=container,proto3" json:"container,omitempty"` // derived container id; "" if none
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcContext) Reset() {
	*x = ProcContext{}
	mi := &file_event_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcContext) ProtoMessage() {}

func (x *ProcContext) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcContext.ProtoReflect.Descriptor instead.
func (*ProcContext) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{23}
}

func (x *ProcContext) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProcContext) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ProcContext) GetPidNs() uint64 {
	if x != nil {
		return x.PidNs
	}
	return 0
}

func (x *ProcContext) GetNetNs() uint64 {
	if x != nil {
		return x.NetNs
	}
	return 0
}

func (x *ProcContext) GetMntNs() uint64 {
	if x != nil {
		return x.MntNs
	}
	return 0
}

func (x *ProcContext) GetUserNs() uint64 {
	if x != nil {
		return x.UserNs
	}
	return 0
}

func (x *ProcContext) GetCgroupNs() uint64 {
	if x != nil {
		return x.CgroupNs
	}
	return 0
}

func (x *ProcContext) GetIpcNs() uint64 {
	if x != nil {
		return x.IpcNs
	}
	return 0
}

func (x *ProcContext) GetUtsNs() uint64 {
	if x != nil {
		return x.UtsNs
	}
	return 0
}

func (x *ProcContext) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *ProcContext) GetCgroup() string {
	if x != nil {
		return x.Cgroup
	}
	return ""
}

func (x *ProcContext) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

// ─── File descriptors ───────────────────────────────────────────────────────
type FdEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            int32                  `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`   // "file" | "socket" | "pipe" | "epoll" | "timer" | "event"
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`   // full path or remote address
	Flags         string                 `protobuf:"bytes,4,opt,name=flags,proto3" json:"flags,omitempty"` // "O_RDONLY" | "O_WRONLY" | "O_RDWR"
	Bytes         uint64                 `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	AgeMs         int64                  `protobuf:"varint,6,opt,name=age_ms,json=ageMs,proto3" json:"age_ms,omitempty"`
	Active        bool                   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"` // had activity in the last cycle
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FdEntry) Reset() {
	*x = FdEntry{}
	mi := &file_event_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FdEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FdEntry) ProtoMessage() {}

func (x *FdEntry) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FdEntry.ProtoReflect.Descriptor instead.
func (*FdEntry) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{24}
}

func (x *FdEntry) GetFd() int32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *FdEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FdEntry) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *FdEntry) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *FdEntry) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *FdEntry) GetAgeMs() int64 {
	if x != nil {
		return x.AgeMs
	}
	return 0
}

func (x *FdEntry) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type FdSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fds           []*FdEntry             `protobuf:"bytes,1,rep,name=fds,proto3" json:"fds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FdSnapshot) Reset() {
	*x = FdSnapshot{}
	mi := &file_event_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FdSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FdSnapshot) ProtoMessage() {}

func (x *FdSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FdSnapshot.ProtoReflect.Descriptor instead.
func (*FdSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{25}
}

func (x *FdSnapshot) GetFds() []*FdEntry {
	if x != nil {
		return x.Fds
	}
	return nil
}

// FdEvent is a change notification (openat/close/dup2/...); its timestamp is on
// the Event envelope.
type FdEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FdEvent) Reset() {
	*x = FdEvent{}
	mi := &file_event_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FdEvent) ProtoMessage() {}

func (x *FdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FdEvent.ProtoReflect.Descriptor instead.
func (*FdEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{26}
}

func (x *FdEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ─── Locks (futex) ──────────────────────────────────────────────────────────
type LockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uaddr         uint64                 `protobuf:"varint,1,opt,name=uaddr,proto3" json:"uaddr,omitempty"`                           // futex word virtual address (no symbols → shown in hex)
	Waiters       uint64                 `protobuf:"varint,2,opt,name=waiters,proto3" json:"waiters,omitempty"`                       // cumulative wait_count
	Wakers        uint64                 `protobuf:"varint,3,opt,name=wakers,proto3" json:"wakers,omitempty"`                         // cumulative wake_count
	WaitDelta     uint64                 `protobuf:"varint,4,opt,name=wait_delta,json=waitDelta,proto3" json:"wait_delta,omitempty"`  // new waits in the current window
	LatencyMs     float64                `protobuf:"fixed64,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"` // average per call
	LastWaitTid   int32                  `protobuf:"varint,6,opt,name=last_wait_tid,json=lastWaitTid,proto3" json:"last_wait_tid,omitempty"`
	LastWakeTid   int32                  `protobuf:"varint,7,opt,name=last_wake_tid,json=lastWakeTid,proto3" json:"last_wake_tid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockEntry) Reset() {
	*x = LockEntry{}
	mi := &file_event_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockEntry) ProtoMessage() {}

func (x *LockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockEntry.ProtoReflect.Descriptor instead.
func (*LockEntry) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{27}
}

func (x *LockEntry) GetUaddr() uint64 {
	if x != nil {
		return x.Uaddr
	}
	return 0
}

func (x *LockEntry) GetWaiters() uint64 {
	if x != nil {
		return x.Waiters
	}
	return 0
}

func (x *LockEntry) GetWakers() uint64 {
	if x != nil {
		return x.Wakers
	}
	return 0
}

func (x *LockEntry) GetWaitDelta() uint64 {
	if x != nil {
		return x.WaitDelta
	}
	return 0
}

func (x *LockEntry) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *LockEntry) GetLastWaitTid() int32 {
	if x != nil {
		return x.LastWaitTid
	}
	return 0
}

func (x *LockEntry) GetLastWakeTid() int32 {
	if x != nil {
		return x.LastWakeTid
	}
	return 0
}

type LockSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locks         []*LockEntry           `protobuf:"bytes,1,rep,name=locks,proto3" json:"locks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSnapshot) Reset() {
	*x = LockSnapshot{}
	mi := &file_event_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSnapshot) ProtoMessage() {}

func (x *LockSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSnapshot.ProtoReflect.Descriptor instead.
func (*LockSnapshot) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{28}
}

func (x *LockSnapshot) GetLocks() []*LockEntry {
	if x != nil {
		return x.Locks
	}
	return nil
}

// ─── Timeline ───────────────────────────────────────────────────────────────
// TimelineEvent's category and timestamp live on the Event envelope.
type TimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEvent) Reset() {
	*x = TimelineEvent{}
	mi := &file_event_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEvent) ProtoMessage() {}

func (x *TimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEvent.ProtoReflect.Descriptor instead.
func (*TimelineEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{29}
}

func (x *TimelineEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\aptop.v1\"@\n" +
	"\bStackRef\x12\x19\n" +
	"\bstack_id\x18\x01 \x01(\x04R\astackId\x12\x19\n" +
	"\bbuild_id\x18\x02 \x01(\tR\abuildId\"\x93\x01\n" +
	"\n" +
	"StackFrame\x12\x12\n" +
	"\x04func\x18\x01 \x01(\tR\x04func\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x16\n" +
	"\x06module\x18\x04 \x01(\tR\x06module\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offset\x12\x19\n" +
	"\bbuild_id\x18\x06 \x01(\tR\abuildId\"\xa4\t\n" +
	"\x05Event\x12 \n" +
	"\fts_unix_nano\x18\x01 \x01(\x03R\n" +
	"tsUnixNano\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03tid\x18\x03 \x01(\x05R\x03tid\x12-\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x11.ptop.v1.CategoryR\bcategory\x12'\n" +
	"\x05stack\x18\x05 \x01(\v2\x11.ptop.v1.StackRefR\x05stack\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\a \x01(\rR\x03gid\x12\x1b\n" +
	"\tcgroup_id\x18\b \x01(\x04R\bcgroupId\x12&\n" +
	"\x03cpu\x18\n" +
	" \x01(\v2\x12.ptop.v1.CpuSampleH\x00R\x03cpu\x126\n" +
	"\bsyscalls\x18\v \x01(\v2\x18.ptop.v1.SyscallSnapshotH\x00R\bsyscalls\x124\n" +
	"\anetwork\x18\f \x01(\v2\x18.ptop.v1.NetworkSnapshotH\x00R\anetwork\x12+\n" +
	"\x06memory\x18\r \x01(\v2\x11.ptop.v1.MemStatsH\x00R\x06memory\x123\n" +
	"\athreads\x18\x0e \x01(\v2\x17.ptop.v1.ThreadSnapshotH\x00R\athreads\x120\n" +
	"\aio_wait\x18\x0f \x01(\v2\x15.ptop.v1.IoWaitSampleH\x00R\x06ioWait\x12B\n" +
	"\rio_throughput\x18\x10 \x01(\v2\x1b.ptop.v1.IoThroughputSampleH\x00R\fioThroughput\x12%\n" +
	"\x02io\x18\x11 \x01(\v2\x13.ptop.v1.IoSnapshotH\x00R\x02io\x12'\n" +
	"\x03fds\x18\x12 \x01(\v2\x13.ptop.v1.FdSnapshotH\x00R\x03fds\x12-\n" +
	"\bfd_event\x18\x13 \x01(\v2\x10.ptop.v1.FdEventH\x00R\afdEvent\x12-\n" +
	"\x05locks\x18\x14 \x01(\v2\x15.ptop.v1.LockSnapshotH\x00R\x05locks\x124\n" +
	"\btimeline\x18\x15 \x01(\v2\x16.ptop.v1.TimelineEventH\x00R\btimeline\x12+\n" +
	"\x04heap\x18\x16 \x01(\v2\x15.ptop.v1.HeapSnapshotH\x00R\x04heap\x123\n" +
	"\n" +
	"heap_event\x18\x17 \x01(\v2\x12.ptop.v1.HeapEventH\x00R\theapEvent\x125\n" +
	"\tnet_error\x18\x18 \x01(\v2\x16.ptop.v1.NetErrorEventH\x00R\bnetError\x12-\n" +
	"\bfs_event\x18\x19 \x01(\v2\x10.ptop.v1.FSEventH\x00R\afsEvent\x12.\n" +
	"\x06signal\x18\x1a \x01(\v2\x14.ptop.v1.SignalEventH\x00R\x06signal\x12,\n" +
	"\x03tls\x18\x1b \x01(\v2\x18.ptop.v1.TLSPayloadEventH\x00R\x03tls\x129\n" +
	"\fproc_context\x18\x1c \x01(\v2\x14.ptop.v1.ProcContextH\x00R\vprocContextB\t\n" +
	"\apayload\"(\n" +
	"\tCpuSample\x12\x1b\n" +
	"\tusage_pct\x18\x01 \x01(\x01R\busagePct\"V\n" +
	"\vSyscallStat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x1d\n" +
	"\n" +
	"latency_ns\x18\x03 \x01(\x04R\tlatencyNs\"=\n" +
	"\x0fSyscallSnapshot\x12*\n" +
	"\x05stats\x18\x01 \x03(\v2\x14.ptop.v1.SyscallStatR\x05stats\"\xc2\x01\n" +
	"\aNetConn\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06remote\x18\x03 \x01(\tR\x06remote\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12\x19\n" +
	"\btx_bytes\x18\a \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\b \x01(\x04R\arxBytes\"9\n" +
	"\x0fNetworkSnapshot\x12&\n" +
	"\x05conns\x18\x01 \x03(\v2\x10.ptop.v1.NetConnR\x05conns\"z\n" +
	"\rNetErrorEvent\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06remote\x18\x02 \x01(\tR\x06remote\x12 \n" +
	"\vretransmits\x18\x03 \x01(\rR\vretransmits\x12\x1b\n" +
	"\tdetail_ms\x18\x04 \x01(\x01R\bdetailMs\"Y\n" +
	"\x0fTLSPayloadEvent\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\tR\x03dir\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x05R\x02fd\x12\x10\n" +
	"\x03len\x18\x03 \x01(\x05R\x03len\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\x89\x01\n" +
	"\bMemStats\x12\x1b\n" +
	"\trss_bytes\x18\x01 \x01(\x04R\brssBytes\x12\x1d\n" +
	"\n" +
	"heap_bytes\x18\x02 \x01(\x04R\theapBytes\x12\x1f\n" +
	"\vpage_faults\x18\x03 \x01(\x04R\n" +
	"pageFaults\x12 \n" +
	"\fallocs_per_s\x18\x04 \x01(\x04R\n" +
	"allocsPerS\"\x97\x01\n" +
	"\tHeapEvent\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\x04R\x04addr\x12\x1f\n" +
	"\vlifetime_ms\x18\x04 \x01(\x01R\n" +
	"lifetimeMs\x12\x1b\n" +
	"\tcall_site\x18\x05 \x01(\x04R\bcallSite\x12\x14\n" +
	"\x05large\x18\x06 \x01(\bR\x05large\"\xd3\x02\n" +
	"\fHeapCallSite\x12\x1b\n" +
	"\tcall_site\x18\x01 \x01(\x04R\bcallSite\x12\x19\n" +
	"\baddr_hex\x18\x02 \x01(\tR\aaddrHex\x12\x1d\n" +
	"\n" +
	"live_bytes\x18\x03 \x01(\x04R\tliveBytes\x12\x1f\n" +
	"\valloc_count\x18\x04 \x01(\x04R\n" +
	"allocCount\x12&\n" +
	"\x0favg_lifetime_ms\x18\x05 \x01(\x01R\ravgLifetimeMs\x12\x1c\n" +
	"\tsuspected\x18\x06 \x01(\bR\tsuspected\x12\x12\n" +
	"\x04func\x18\a \x01(\tR\x04func\x12\x12\n" +
	"\x04file\x18\b \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\t \x01(\x05R\x04line\x12\x16\n" +
	"\x06module\x18\n" +
	" \x01(\tR\x06module\x12\x16\n" +
	"\x06offset\x18\v \x01(\x04R\x06offset\x12\x19\n" +
	"\bstack_id\x18\f \x01(\x04R\astackId\"\xc4\x01\n" +
	"\fHeapSnapshot\x12&\n" +
	"\x0flive_heap_bytes\x18\x01 \x01(\x04R\rliveHeapBytes\x12\x1d\n" +
	"\n" +
	"alloc_rate\x18\x02 \x01(\x01R\tallocRate\x120\n" +
	"\x14suspected_leak_bytes\x18\x03 \x01(\x04R\x12suspectedLeakBytes\x12;\n" +
	"\x0etop_call_sites\x18\x04 \x03(\v2\x15.ptop.v1.HeapCallSiteR\ftopCallSites\"\x9e\x01\n" +
	"\n" +
	"ThreadInfo\x12\x10\n" +
	"\x03tid\x18\x01 \x01(\x05R\x03tid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x17\n" +
	"\acpu_pct\x18\x04 \x01(\x01R\x06cpuPct\x12\x18\n" +
	"\awaiting\x18\x05 \x01(\tR\awaiting\x12!\n" +
	"\fctx_switches\x18\x06 \x01(\x04R\vctxSwitches\"?\n" +
	"\x0eThreadSnapshot\x12-\n" +
	"\athreads\x18\x01 \x03(\v2\x13.ptop.v1.ThreadInfoR\athreads\" \n" +
	"\fIoWaitSample\x12\x10\n" +
	"\x03pct\x18\x01 \x01(\x01R\x03pct\"\xa0\x01\n" +
	"\x12IoThroughputSample\x12'\n" +
	"\x10read_bytes_per_s\x18\x01 \x01(\x01R\rreadBytesPerS\x12)\n" +
	"\x11write_bytes_per_s\x18\x02 \x01(\x01R\x0ewriteBytesPerS\x12\x19\n" +
	"\bread_ops\x18\x03 \x01(\x04R\areadOps\x12\x1b\n" +
	"\twrite_ops\x18\x04 \x01(\x04R\bwriteOps\"\xb0\x01\n" +
	"\vIoFileStats\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05reads\x18\x03 \x01(\x04R\x05reads\x12\x16\n" +
	"\x06writes\x18\x04 \x01(\x04R\x06writes\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x04R\x05bytes\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12\x16\n" +
	"\x06fsyncs\x18\a \x01(\x04R\x06fsyncs\"O\n" +
	"\rLatencyBucket\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04read\x18\x02 \x01(\x01R\x04read\x12\x14\n" +
	"\x05write\x18\x03 \x01(\x01R\x05write\"\xda\x02\n" +
	"\n" +
	"IoSnapshot\x12'\n" +
	"\x10read_bytes_per_s\x18\x01 \x01(\x01R\rreadBytesPerS\x12)\n" +
	"\x11write_bytes_per_s\x18\x02 \x01(\x01R\x0ewriteBytesPerS\x12\x19\n" +
	"\bread_ops\x18\x03 \x01(\x04R\areadOps\x12\x1b\n" +
	"\twrite_ops\x18\x04 \x01(\x04R\bwriteOps\x12\x16\n" +
	"\x06fsyncs\x18\x05 \x01(\x04R\x06fsyncs\x12\x14\n" +
	"\x05opens\x18\x06 \x01(\x04R\x05opens\x12\x1e\n" +
	"\vio_wait_pct\x18\a \x01(\x01R\tioWaitPct\x121\n" +
	"\ttop_files\x18\b \x03(\v2\x14.ptop.v1.IoFileStatsR\btopFiles\x12?\n" +
	"\x0flatency_buckets\x18\t \x03(\v2\x16.ptop.v1.LatencyBucketR\x0elatencyBuckets\"p\n" +
	"\aFSEvent\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_path\x18\x03 \x01(\tR\anewPath\x12\x14\n" +
	"\x05errno\x18\x04 \x01(\x05R\x05errno\x12\x10\n" +
	"\x03err\x18\x05 \x01(\tR\x03err\"\xc6\x01\n" +
	"\vSignalEvent\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\tR\x06signal\x12\x14\n" +
	"\x05signo\x18\x02 \x01(\x05R\x05signo\x12\x1d\n" +
	"\n" +
	"sender_pid\x18\x03 \x01(\x05R\tsenderPid\x12\x1f\n" +
	"\vsender_comm\x18\x04 \x01(\tR\n" +
	"senderComm\x12\x1d\n" +
	"\n" +
	"target_tid\x18\x05 \x01(\x05R\ttargetTid\x12\x12\n" +
	"\x04code\x18\x06 \x01(\x05R\x04code\x12\x16\n" +
	"\x06result\x18\a \x01(\x05R\x06result\"\xad\x02\n" +
	"\vProcContext\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x02 \x01(\rR\x03gid\x12\x15\n" +
	"\x06pid_ns\x18\x03 \x01(\x04R\x05pidNs\x12\x15\n" +
	"\x06net_ns\x18\x04 \x01(\x04R\x05netNs\x12\x15\n" +
	"\x06mnt_ns\x18\x05 \x01(\x04R\x05mntNs\x12\x17\n" +
	"\auser_ns\x18\x06 \x01(\x04R\x06userNs\x12\x1b\n" +
	"\tcgroup_ns\x18\a \x01(\x04R\bcgroupNs\x12\x15\n" +
	"\x06ipc_ns\x18\b \x01(\x04R\x05ipcNs\x12\x15\n" +
	"\x06uts_ns\x18\t \x01(\x04R\x05utsNs\x12\x1b\n" +
	"\tcgroup_id\x18\n" +
	" \x01(\x04R\bcgroupId\x12\x16\n" +
	"\x06cgroup\x18\v \x01(\tR\x06cgroup\x12\x1c\n" +
	"\tcontainer\x18\f \x01(\tR\tcontainer\"\x9c\x01\n" +
	"\aFdEntry\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x05R\x02fd\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\tR\x05flags\x12\x14\n" +
	"\x05bytes\x18\x05 \x01(\x04R\x05bytes\x12\x15\n" +
	"\x06age_ms\x18\x06 \x01(\x03R\x05ageMs\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\"0\n" +
	"\n" +
	"FdSnapshot\x12\"\n" +
	"\x03fds\x18\x01 \x03(\v2\x10.ptop.v1.FdEntryR\x03fds\"#\n" +
	"\aFdEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd9\x01\n" +
	"\tLockEntry\x12\x14\n" +
	"\x05uaddr\x18\x01 \x01(\x04R\x05uaddr\x12\x18\n" +
	"\awaiters\x18\x02 \x01(\x04R\awaiters\x12\x16\n" +
	"\x06wakers\x18\x03 \x01(\x04R\x06wakers\x12\x1d\n" +
	"\n" +
	"wait_delta\x18\x04 \x01(\x04R\twaitDelta\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x01R\tlatencyMs\x12\"\n" +
	"\rlast_wait_tid\x18\x06 \x01(\x05R\vlastWaitTid\x12\"\n" +
	"\rlast_wake_tid\x18\a \x01(\x05R\vlastWakeTid\"8\n" +
	"\fLockSnapshot\x12(\n" +
	"\x05locks\x18\x01 \x03(\v2\x12.ptop.v1.LockEntryR\x05locks\")\n" +
	"\rTimelineEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x83\x02\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCATEGORY_CPU\x10\x01\x12\x14\n" +
	"\x10CATEGORY_SYSCALL\x10\x02\x12\x14\n" +
	"\x10CATEGORY_NETWORK\x10\x03\x12\x13\n" +
	"\x0fCATEGORY_MEMORY\x10\x04\x12\x13\n" +
	"\x0fCATEGORY_THREAD\x10\x05\x12\x0f\n" +
	"\vCATEGORY_IO\x10\x06\x12\x0f\n" +
	"\vCATEGORY_FD\x10\a\x12\x11\n" +
	"\rCATEGORY_LOCK\x10\b\x12\x15\n" +
	"\x11CATEGORY_TIMELINE\x10\t\x12\x13\n" +
	"\x0fCATEGORY_SIGNAL\x10\n" +
	"\x12\x14\n" +
	"\x10CATEGORY_PROCESS\x10\vB\x85\x01\n" +
	"\vcom.ptop.v1B\n" +
	"EventProtoP\x01Z-github.com/trentas/ptop/pkg/streampb;streampb\xa2\x02\x03PXX\xaa\x02\aPtop.V1\xca\x02\aPtop\\V1\xe2\x02\x13Ptop\\V1\\GPBMetadata\xea\x02\bPtop::V1b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_event_proto_goTypes = []any{
	(Category)(0),              // 0: ptop.v1.Category
	(*StackRef)(nil),           // 1: ptop.v1.StackRef
	(*StackFrame)(nil),         // 2: ptop.v1.StackFrame
	(*Event)(nil),              // 3: ptop.v1.Event
	(*CpuSample)(nil),          // 4: ptop.v1.CpuSample
	(*SyscallStat)(nil),        // 5: ptop.v1.SyscallStat
	(*SyscallSnapshot)(nil),    // 6: ptop.v1.SyscallSnapshot
	(*NetConn)(nil),            // 7: ptop.v1.NetConn
	(*NetworkSnapshot)(nil),    // 8: ptop.v1.NetworkSnapshot
	(*NetErrorEvent)(nil),      // 9: ptop.v1.NetErrorEvent
	(*TLSPayloadEvent)(nil),    // 10: ptop.v1.TLSPayloadEvent
	(*MemStats)(nil),           // 11: ptop.v1.MemStats
	(*HeapEvent)(nil),          // 12: ptop.v1.HeapEvent
	(*HeapCallSite)(nil),       // 13: ptop.v1.HeapCallSite
	(*HeapSnapshot)(nil),       // 14: ptop.v1.HeapSnapshot
	(*ThreadInfo)(nil),         // 15: ptop.v1.ThreadInfo
	(*ThreadSnapshot)(nil),     // 16: ptop.v1.ThreadSnapshot
	(*IoWaitSample)(nil),       // 17: ptop.v1.IoWaitSample
	(*IoThroughputSample)(nil), // 18: ptop.v1.IoThroughputSample
	(*IoFileStats)(nil),        // 19: ptop.v1.IoFileStats
	(*LatencyBucket)(nil),      // 20: ptop.v1.LatencyBucket
	(*IoSnapshot)(nil),         // 21: ptop.v1.IoSnapshot
	(*FSEvent)(nil),            // 22: ptop.v1.FSEvent
	(*SignalEvent)(nil),        // 23: ptop.v1.SignalEvent
	(*ProcContext)(nil),        // 24: ptop.v1.ProcContext
	(*FdEntry)(nil),            // 25: ptop.v1.FdEntry
	(*FdSnapshot)(nil),         // 26: ptop.v1.FdSnapshot
	(*FdEvent)(nil),            // 27: ptop.v1.FdEvent
	(*LockEntry)(nil),          // 28: ptop.v1.LockEntry
	(*LockSnapshot)(nil),       // 29: ptop.v1.LockSnapshot
	(*TimelineEvent)(nil),      // 30: ptop.v1.TimelineEvent
}
var file_event_proto_depIdxs = []int32{
	0,  // 0: ptop.v1.Event.category:type_name -> ptop.v1.Category
	1,  // 1: ptop.v1.Event.stack:type_name -> ptop.v1.StackRef
	4,  // 2: ptop.v1.Event.cpu:type_name -> ptop.v1.CpuSample
	6,  // 3: ptop.v1.Event.syscalls:type_name -> ptop.v1.SyscallSnapshot
	8,  // 4: ptop.v1.Event.network:type_name -> ptop.v1.NetworkSnapshot
	11, // 5: ptop.v1.Event.memory:type_name -> ptop.v1.MemStats
	16, // 6: ptop.v1.Event.threads:type_name -> ptop.v1.ThreadSnapshot
	17, // 7: ptop.v1.Event.io_wait:type_name -> ptop.v1.IoWaitSample
	18, // 8: ptop.v1.Event.io_throughput:type_name -> ptop.v1.IoThroughputSample
	21, // 9: ptop.v1.Event.io:type_name -> ptop.v1.IoSnapshot
	26, // 10: ptop.v1.Event.fds:type_name -> ptop.v1.FdSnapshot
	27, // 11: ptop.v1.Event.fd_event:type_name -> ptop.v1.FdEvent
	29, // 12: ptop.v1.Event.locks:type_name -> ptop.v1.LockSnapshot
	30, // 13: ptop.v1.Event.timeline:type_name -> ptop.v1.TimelineEvent
	14, // 14: ptop.v1.Event.heap:type_name -> ptop.v1.HeapSnapshot
	12, // 15: ptop.v1.Event.heap_event:type_name -> ptop.v1.HeapEvent
	9,  // 16: ptop.v1.Event.net_error:type_name -> ptop.v1.NetErrorEvent
	22, // 17: ptop.v1.Event.fs_event:type_name -> ptop.v1.FSEvent
	23, // 18: ptop.v1.Event.signal:type_name -> ptop.v1.SignalEvent
	10, // 19: ptop.v1.Event.tls:type_name -> ptop.v1.TLSPayloadEvent
	24, // 20: ptop.v1.Event.proc_context:type_name -> ptop.v1.ProcContext
	5,  // 21: ptop.v1.SyscallSnapshot.stats:type_name -> ptop.v1.SyscallStat
	7,  // 22: ptop.v1.NetworkSnapshot.conns:type_name -> ptop.v1.NetConn
	13, // 23: ptop.v1.HeapSnapshot.top_call_sites:type_name -> ptop.v1.HeapCallSite
	15, // 24: ptop.v1.ThreadSnapshot.threads:type_name -> ptop.v1.ThreadInfo
	19, // 25: ptop.v1.IoSnapshot.top_files:type_name -> ptop.v1.IoFileStats
	20, // 26: ptop.v1.IoSnapshot.latency_buckets:type_name -> ptop.v1.LatencyBucket
	25, // 27: ptop.v1.FdSnapshot.fds:type_name -> ptop.v1.FdEntry
	28, // 28: ptop.v1.LockSnapshot.locks:type_name -> ptop.v1.LockEntry
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	file_event_proto_msgTypes[2].OneofWrappers = []any{
		(*Event_Cpu)(nil),
		(*Event_Syscalls)(nil),
		(*Event_Network)(nil),
		(*Event_Memory)(nil),
		(*Event_Threads)(nil),
		(*Event_IoWait)(nil),
		(*Event_IoThroughput)(nil),
		(*Event_Io)(nil),
		(*Event_Fds)(nil),
		(*Event_FdEvent)(nil),
		(*Event_Locks)(nil),
		(*Event_Timeline)(nil),
		(*Event_Heap)(nil),
		(*Event_HeapEvent)(nil),
		(*Event_NetError)(nil),
		(*Event_FsEvent)(nil),
		(*Event_Signal)(nil),
		(*Event_Tls)(nil),
		(*Event_ProcContext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		EnumInfos:         file_event_proto_enumTypes,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
