// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service.proto

package streampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TargetMode is how the server was told what to observe (#94).
type TargetMode int32

const (
	TargetMode_TARGET_MODE_UNSPECIFIED TargetMode = 0
	// One process, matched by pid inside its own pid namespace.
	TargetMode_TARGET_MODE_PID TargetMode = 1
	// Every process in a cgroup subtree, matched by cgroup id. No pid is
	// involved, so the subtree's forks are included automatically.
	TargetMode_TARGET_MODE_CGROUP TargetMode = 2
)

// Enum value maps for TargetMode.
var (
	TargetMode_name = map[int32]string{
		0: "TARGET_MODE_UNSPECIFIED",
		1: "TARGET_MODE_PID",
		2: "TARGET_MODE_CGROUP",
	}
	TargetMode_value = map[string]int32{
		"TARGET_MODE_UNSPECIFIED": 0,
		"TARGET_MODE_PID":         1,
		"TARGET_MODE_CGROUP":      2,
	}
)

func (x TargetMode) Enum() *TargetMode {
	p := new(TargetMode)
	*p = x
	return p
}

func (x TargetMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetMode) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (TargetMode) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x TargetMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetMode.Descriptor instead.
func (TargetMode) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// ProbeState is what became of one collector for one target (#112).
//
// The three ways a subsystem goes quiet are unrelated and call for opposite
// reactions — a probe the operator switched off is a knob they can turn back
// on, one that failed to attach is a broken deployment, and a target that
// simply did not do the thing is the only one that is a finding. Before this
// existed all three reached a consumer as the same absence.
type ProbeState int32

const (
	ProbeState_PROBE_STATE_UNSPECIFIED ProbeState = 0
	// Attached, and producing events for this target.
	ProbeState_PROBE_STATE_ACTIVE ProbeState = 1
	// Not asked for: named in --disable, or needing an eBPF lane --no-ebpf turned
	// off, or opt-in and not opted into (--tls).
	ProbeState_PROBE_STATE_DISABLED ProbeState = 2
	// Asked for and could not attach: missing capabilities, no tracefs, kernel
	// too old, no symbol to hook. The target is instrumented less than requested,
	// and nothing but this field says so after the fact.
	ProbeState_PROBE_STATE_FAILED ProbeState = 3
	// Cannot exist here: this build embeds no eBPF programs, the platform has no
	// such source, or the scope structurally excludes it (a uprobe into one
	// process's mapped libc has no meaning over a cgroup subtree).
	ProbeState_PROBE_STATE_UNSUPPORTED ProbeState = 4
)

// Enum value maps for ProbeState.
var (
	ProbeState_name = map[int32]string{
		0: "PROBE_STATE_UNSPECIFIED",
		1: "PROBE_STATE_ACTIVE",
		2: "PROBE_STATE_DISABLED",
		3: "PROBE_STATE_FAILED",
		4: "PROBE_STATE_UNSUPPORTED",
	}
	ProbeState_value = map[string]int32{
		"PROBE_STATE_UNSPECIFIED": 0,
		"PROBE_STATE_ACTIVE":      1,
		"PROBE_STATE_DISABLED":    2,
		"PROBE_STATE_FAILED":      3,
		"PROBE_STATE_UNSUPPORTED": 4,
	}
)

func (x ProbeState) Enum() *ProbeState {
	p := new(ProbeState)
	*p = x
	return p
}

func (x ProbeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (ProbeState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x ProbeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeState.Descriptor instead.
func (ProbeState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

// SubscribeRequest opens a stream. categories filters which Event categories
// the server sends; empty means all.
//
// pid names the process to observe (#72). It is required when the server was
// started without a target (`ptop --serve` with no `--pid`/`--cgroup`), which
// serves targets on demand: the collectors for a pid start with its first
// subscriber and stop with its last. When the server WAS started with a fixed
// target, pid must be 0 or that exact pid — anything else is rejected rather
// than silently served the wrong process. Either way the server reports what it
// is actually observing in the TargetInfo handshake.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []Category             `protobuf:"varint,1,rep,packed,name=categories,proto3,enum=ptop.v1.Category" json:"categories,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *SubscribeRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// TargetInfo describes the SCOPE of everything on this stream. The server sends
// it once, in the first StreamMeta of a subscription, before any event.
//
// It matters because the two modes aggregate differently. In PID mode every
// Event.pid is the target. In CGROUP mode events come from any process in the
// subtree, so Event.pid is 0 on the aggregate payloads (there is no single
// process to name) and any pid inside a payload is a ROOT-namespace pid — a
// subtree can span pid namespaces, so there is no namespace to project into.
type TargetInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  TargetMode             `protobuf:"varint,1,opt,name=mode,proto3,enum=ptop.v1.TargetMode" json:"mode,omitempty"`
	// PID mode: the target pid. 0 in cgroup mode.
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// CGROUP mode: the resolved absolute cgroup path, and the cgroup id it
	// resolved to (the directory inode). Empty/0 in pid mode.
	CgroupPath string `protobuf:"bytes,3,opt,name=cgroup_path,json=cgroupPath,proto3" json:"cgroup_path,omitempty"`
	CgroupId   uint64 `protobuf:"varint,4,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	// Every collector this server tried to run for the target and what became of
	// it, sorted by name (#112). Empty from a server older than that.
	//
	// This is the second half of the scope, for the same reason as the first: a
	// probe that is not running emits nothing, which in the events alone is
	// indistinguishable from a target that never did the thing. A consumer
	// comparing two captures must compare their probe sets before their numbers,
	// or it reports the change of instrumentation as a change in behaviour.
	Probes        []*ProbeInfo `protobuf:"bytes,5,rep,name=probes,proto3" json:"probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetInfo) Reset() {
	*x = TargetInfo{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInfo) ProtoMessage() {}

func (x *TargetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetInfo.ProtoReflect.Descriptor instead.
func (*TargetInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *TargetInfo) GetMode() TargetMode {
	if x != nil {
		return x.Mode
	}
	return TargetMode_TARGET_MODE_UNSPECIFIED
}

func (x *TargetInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *TargetInfo) GetCgroupPath() string {
	if x != nil {
		return x.CgroupPath
	}
	return ""
}

func (x *TargetInfo) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

func (x *TargetInfo) GetProbes() []*ProbeInfo {
	if x != nil {
		return x.Probes
	}
	return nil
}

// ProbeInfo is one collector's outcome for the target of this stream.
type ProbeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subsystem name, spelled as --disable accepts it: cpu, threads, memory,
	// heap, syscalls, io, network, futex, signals, lifecycle, security, tls, fd.
	Name  string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State ProbeState `protobuf:"varint,2,opt,name=state,proto3,enum=ptop.v1.ProbeState" json:"state,omitempty"`
	// Where an ACTIVE probe's numbers come from: "eBPF" or "/proc". Empty
	// otherwise. The same subsystem read through different sources is not the
	// same measurement, so this is part of the comparison key too.
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Why a probe that is not ACTIVE is not running — the attach error, or the
	// flag that switched it off. Operator-facing prose; do not parse it.
	Detail        string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeInfo) Reset() {
	*x = ProbeInfo{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeInfo) ProtoMessage() {}

func (x *ProbeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeInfo.ProtoReflect.Descriptor instead.
func (*ProbeInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProbeInfo) GetState() ProbeState {
	if x != nil {
		return x.State
	}
	return ProbeState_PROBE_STATE_UNSPECIFIED
}

func (x *ProbeInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProbeInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// StreamMeta is an out-of-band signal interleaved in the stream. It carries the
// subscription handshake (target, sent once before any event) and reports
// backpressure: how many events the server dropped for this subscriber because
// it could not keep up (cumulative). The collector is never blocked by a slow
// consumer — events are dropped and counted instead.
type StreamMeta struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Dropped uint64                 `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// Set on the handshake meta only; nil on backpressure notices.
	Target        *TargetInfo `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMeta) Reset() {
	*x = StreamMeta{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMeta) ProtoMessage() {}

func (x *StreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMeta.ProtoReflect.Descriptor instead.
func (*StreamMeta) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMeta) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *StreamMeta) GetTarget() *TargetInfo {
	if x != nil {
		return x.Target
	}
	return nil
}

// SubscribeResponse is one item in the stream: either a captured Event or a
// StreamMeta backpressure notice.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SubscribeResponse_Event
	//	*SubscribeResponse_Meta
	Kind          isSubscribeResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeResponse) GetKind() isSubscribeResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SubscribeResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *SubscribeResponse) GetMeta() *StreamMeta {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

type isSubscribeResponse_Kind interface {
	isSubscribeResponse_Kind()
}

type SubscribeResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type SubscribeResponse_Meta struct {
	Meta *StreamMeta `protobuf:"bytes,2,opt,name=meta,proto3,oneof"`
}

func (*SubscribeResponse_Event) isSubscribeResponse_Kind() {}

func (*SubscribeResponse_Meta) isSubscribeResponse_Kind() {}

// ResolveStackRequest asks the server to symbolize a stack id referenced by an
// event (Event.stack.stack_id, HeapCallSite.stack_id or LockEntry.stack_id).
// The id is only valid for the build identified by the accompanying
// StackRef.build_id, and is namespaced per capturing tracer — pass back exactly
// the value the event carried, never a bare kernel id.
type ResolveStackRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StackId uint64                 `protobuf:"varint,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	// The process the stack was captured in (#72). Kernel stack maps are
	// per-target, so the same id means different stacks in different processes:
	// required on an on-demand server, and on a fixed-target server it must be 0
	// or the server's own pid.
	Pid           int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveStackRequest) Reset() {
	*x = ResolveStackRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveStackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveStackRequest) ProtoMessage() {}

func (x *ResolveStackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveStackRequest.ProtoReflect.Descriptor instead.
func (*ResolveStackRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveStackRequest) GetStackId() uint64 {
	if x != nil {
		return x.StackId
	}
	return 0
}

func (x *ResolveStackRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// ResolveStackResponse returns the leaf-first symbolized frames for the stack
// id. found is false when the id is unknown — evicted from the kernel stack
// map, never captured, or symbolization is unavailable on the server.
type ResolveStackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frames        []*StackFrame          `protobuf:"bytes,1,rep,name=frames,proto3" json:"frames,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveStackResponse) Reset() {
	*x = ResolveStackResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveStackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveStackResponse) ProtoMessage() {}

func (x *ResolveStackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveStackResponse.ProtoReflect.Descriptor instead.
func (*ResolveStackResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveStackResponse) GetFrames() []*StackFrame {
	if x != nil {
		return x.Frames
	}
	return nil
}

func (x *ResolveStackResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aptop.v1\x1a\vevent.proto\"W\n" +
	"\x10SubscribeRequest\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\x0e2\x11.ptop.v1.CategoryR\n" +
	"categories\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"\xb1\x01\n" +
	"\n" +
	"TargetInfo\x12'\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x13.ptop.v1.TargetModeR\x04mode\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x1f\n" +
	"\vcgroup_path\x18\x03 \x01(\tR\n" +
	"cgroupPath\x12\x1b\n" +
	"\tcgroup_id\x18\x04 \x01(\x04R\bcgroupId\x12*\n" +
	"\x06probes\x18\x05 \x03(\v2\x12.ptop.v1.ProbeInfoR\x06probes\"z\n" +
	"\tProbeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x05state\x18\x02 \x01(\x0e2\x13.ptop.v1.ProbeStateR\x05state\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\"S\n" +
	"\n" +
	"StreamMeta\x12\x18\n" +
	"\adropped\x18\x01 \x01(\x04R\adropped\x12+\n" +
	"\x06target\x18\x02 \x01(\v2\x13.ptop.v1.TargetInfoR\x06target\"n\n" +
	"\x11SubscribeResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x0e.ptop.v1.EventH\x00R\x05event\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.ptop.v1.StreamMetaH\x00R\x04metaB\x06\n" +
	"\x04kind\"B\n" +
	"\x13ResolveStackRequest\x12\x19\n" +
	"\bstack_id\x18\x01 \x01(\x04R\astackId\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\"Y\n" +
	"\x14ResolveStackResponse\x12+\n" +
	"\x06frames\x18\x01 \x03(\v2\x13.ptop.v1.StackFrameR\x06frames\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found*V\n" +
	"\n" +
	"TargetMode\x12\x1b\n" +
	"\x17TARGET_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTARGET_MODE_PID\x10\x01\x12\x16\n" +
	"\x12TARGET_MODE_CGROUP\x10\x02*\x90\x01\n" +
	"\n" +
	"ProbeState\x12\x1b\n" +
	"\x17PROBE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROBE_STATE_ACTIVE\x10\x01\x12\x18\n" +
	"\x14PROBE_STATE_DISABLED\x10\x02\x12\x16\n" +
	"\x12PROBE_STATE_FAILED\x10\x03\x12\x1b\n" +
	"\x17PROBE_STATE_UNSUPPORTED\x10\x042\xa7\x01\n" +
	"\x12EventStreamService\x12D\n" +
	"\tSubscribe\x12\x19.ptop.v1.SubscribeRequest\x1a\x1a.ptop.v1.SubscribeResponse0\x01\x12K\n" +
	"\fResolveStack\x12\x1c.ptop.v1.ResolveStackRequest\x1a\x1d.ptop.v1.ResolveStackResponseB\x87\x01\n" +
	"\vcom.ptop.v1B\fServiceProtoP\x01Z-github.com/trentas/ptop/pkg/streampb;streampb\xa2\x02\x03PXX\xaa\x02\aPtop.V1\xca\x02\aPtop\\V1\xe2\x02\x13Ptop\\V1\\GPBMetadata\xea\x02\bPtop::V1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_proto_goTypes = []any{
	(TargetMode)(0),              // 0: ptop.v1.TargetMode
	(ProbeState)(0),              // 1: ptop.v1.ProbeState
	(*SubscribeRequest)(nil),     // 2: ptop.v1.SubscribeRequest
	(*TargetInfo)(nil),           // 3: ptop.v1.TargetInfo
	(*ProbeInfo)(nil),            // 4: ptop.v1.ProbeInfo
	(*StreamMeta)(nil),           // 5: ptop.v1.StreamMeta
	(*SubscribeResponse)(nil),    // 6: ptop.v1.SubscribeResponse
	(*ResolveStackRequest)(nil),  // 7: ptop.v1.ResolveStackRequest
	(*ResolveStackResponse)(nil), // 8: ptop.v1.ResolveStackResponse
	(Category)(0),                // 9: ptop.v1.Category
	(*Event)(nil),                // 10: ptop.v1.Event
	(*StackFrame)(nil),           // 11: ptop.v1.StackFrame
}
var file_service_proto_depIdxs = []int32{
	9,  // 0: ptop.v1.SubscribeRequest.categories:type_name -> ptop.v1.Category
	0,  // 1: ptop.v1.TargetInfo.mode:type_name -> ptop.v1.TargetMode
	4,  // 2: ptop.v1.TargetInfo.probes:type_name -> ptop.v1.ProbeInfo
	1,  // 3: ptop.v1.ProbeInfo.state:type_name -> ptop.v1.ProbeState
	3,  // 4: ptop.v1.StreamMeta.target:type_name -> ptop.v1.TargetInfo
	10, // 5: ptop.v1.SubscribeResponse.event:type_name -> ptop.v1.Event
	5,  // 6: ptop.v1.SubscribeResponse.meta:type_name -> ptop.v1.StreamMeta
	11, // 7: ptop.v1.ResolveStackResponse.frames:type_name -> ptop.v1.StackFrame
	2,  // 8: ptop.v1.EventStreamService.Subscribe:input_type -> ptop.v1.SubscribeRequest
	7,  // 9: ptop.v1.EventStreamService.ResolveStack:input_type -> ptop.v1.ResolveStackRequest
	6,  // 10: ptop.v1.EventStreamService.Subscribe:output_type -> ptop.v1.SubscribeResponse
	8,  // 11: ptop.v1.EventStreamService.ResolveStack:output_type -> ptop.v1.ResolveStackResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_event_proto_init()
	file_service_proto_msgTypes[4].OneofWrappers = []any{
		(*SubscribeResponse_Event)(nil),
		(*SubscribeResponse_Meta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
