// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service.proto

package streampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest opens a stream. categories filters which Event categories
// the server sends; empty means all. The target PID is fixed per server
// instance (set via `ptop --serve --pid`), so it is not part of the request.
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []Category             `protobuf:"varint,1,rep,packed,name=categories,proto3,enum=ptop.v1.Category" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetCategories() []Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

// StreamMeta is an out-of-band signal interleaved in the stream. It reports
// backpressure: how many events the server dropped for this subscriber because
// it could not keep up (cumulative). The collector is never blocked by a slow
// consumer — events are dropped and counted instead.
type StreamMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dropped       uint64                 `protobuf:"varint,1,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMeta) Reset() {
	*x = StreamMeta{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMeta) ProtoMessage() {}

func (x *StreamMeta) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMeta.ProtoReflect.Descriptor instead.
func (*StreamMeta) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *StreamMeta) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

// SubscribeResponse is one item in the stream: either a captured Event or a
// StreamMeta backpressure notice.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SubscribeResponse_Event
	//	*SubscribeResponse_Meta
	Kind          isSubscribeResponse_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeResponse) GetKind() isSubscribeResponse_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SubscribeResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *SubscribeResponse) GetMeta() *StreamMeta {
	if x != nil {
		if x, ok := x.Kind.(*SubscribeResponse_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

type isSubscribeResponse_Kind interface {
	isSubscribeResponse_Kind()
}

type SubscribeResponse_Event struct {
	Event *Event `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type SubscribeResponse_Meta struct {
	Meta *StreamMeta `protobuf:"bytes,2,opt,name=meta,proto3,oneof"`
}

func (*SubscribeResponse_Event) isSubscribeResponse_Kind() {}

func (*SubscribeResponse_Meta) isSubscribeResponse_Kind() {}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aptop.v1\x1a\vevent.proto\"E\n" +
	"\x10SubscribeRequest\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\x0e2\x11.ptop.v1.CategoryR\n" +
	"categories\"&\n" +
	"\n" +
	"StreamMeta\x12\x18\n" +
	"\adropped\x18\x01 \x01(\x04R\adropped\"n\n" +
	"\x11SubscribeResponse\x12&\n" +
	"\x05event\x18\x01 \x01(\v2\x0e.ptop.v1.EventH\x00R\x05event\x12)\n" +
	"\x04meta\x18\x02 \x01(\v2\x13.ptop.v1.StreamMetaH\x00R\x04metaB\x06\n" +
	"\x04kind2Z\n" +
	"\x12EventStreamService\x12D\n" +
	"\tSubscribe\x12\x19.ptop.v1.SubscribeRequest\x1a\x1a.ptop.v1.SubscribeResponse0\x01B\x87\x01\n" +
	"\vcom.ptop.v1B\fServiceProtoP\x01Z-github.com/trentas/ptop/pkg/streampb;streampb\xa2\x02\x03PXX\xaa\x02\aPtop.V1\xca\x02\aPtop\\V1\xe2\x02\x13Ptop\\V1\\GPBMetadata\xea\x02\bPtop::V1b\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*SubscribeRequest)(nil),  // 0: ptop.v1.SubscribeRequest
	(*StreamMeta)(nil),        // 1: ptop.v1.StreamMeta
	(*SubscribeResponse)(nil), // 2: ptop.v1.SubscribeResponse
	(Category)(0),             // 3: ptop.v1.Category
	(*Event)(nil),             // 4: ptop.v1.Event
}
var file_service_proto_depIdxs = []int32{
	3, // 0: ptop.v1.SubscribeRequest.categories:type_name -> ptop.v1.Category
	4, // 1: ptop.v1.SubscribeResponse.event:type_name -> ptop.v1.Event
	1, // 2: ptop.v1.SubscribeResponse.meta:type_name -> ptop.v1.StreamMeta
	0, // 3: ptop.v1.EventStreamService.Subscribe:input_type -> ptop.v1.SubscribeRequest
	2, // 4: ptop.v1.EventStreamService.Subscribe:output_type -> ptop.v1.SubscribeResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_event_proto_init()
	file_service_proto_msgTypes[2].OneofWrappers = []any{
		(*SubscribeResponse_Event)(nil),
		(*SubscribeResponse_Meta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
