// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: service.proto

package streampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStreamService_Subscribe_FullMethodName    = "/ptop.v1.EventStreamService/Subscribe"
	EventStreamService_ResolveStack_FullMethodName = "/ptop.v1.EventStreamService/ResolveStack"
)

// EventStreamServiceClient is the client API for EventStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventStreamService is ptop's headless collection surface. ptop runs with the
// elevated capabilities (CAP_BPF/CAP_PERFMON); subscribers connect with none.
type EventStreamServiceClient interface {
	// Subscribe streams collector events for the server's target PID until the
	// client disconnects. Multiple subscribers fan out from one collector.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// ResolveStack symbolizes a stack id seen on the stream into its leaf-first
	// frames — an out-of-band lookup so high-rate events stay small (they carry
	// only the id). Resolution is best-effort; see ResolveStackResponse.found.
	ResolveStack(ctx context.Context, in *ResolveStackRequest, opts ...grpc.CallOption) (*ResolveStackResponse, error)
}

type eventStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamServiceClient(cc grpc.ClientConnInterface) EventStreamServiceClient {
	return &eventStreamServiceClient{cc}
}

func (c *eventStreamServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStreamService_ServiceDesc.Streams[0], EventStreamService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStreamService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *eventStreamServiceClient) ResolveStack(ctx context.Context, in *ResolveStackRequest, opts ...grpc.CallOption) (*ResolveStackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveStackResponse)
	err := c.cc.Invoke(ctx, EventStreamService_ResolveStack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStreamServiceServer is the server API for EventStreamService service.
// All implementations must embed UnimplementedEventStreamServiceServer
// for forward compatibility.
//
// EventStreamService is ptop's headless collection surface. ptop runs with the
// elevated capabilities (CAP_BPF/CAP_PERFMON); subscribers connect with none.
type EventStreamServiceServer interface {
	// Subscribe streams collector events for the server's target PID until the
	// client disconnects. Multiple subscribers fan out from one collector.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// ResolveStack symbolizes a stack id seen on the stream into its leaf-first
	// frames — an out-of-band lookup so high-rate events stay small (they carry
	// only the id). Resolution is best-effort; see ResolveStackResponse.found.
	ResolveStack(context.Context, *ResolveStackRequest) (*ResolveStackResponse, error)
	mustEmbedUnimplementedEventStreamServiceServer()
}

// UnimplementedEventStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamServiceServer struct{}

func (UnimplementedEventStreamServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEventStreamServiceServer) ResolveStack(context.Context, *ResolveStackRequest) (*ResolveStackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveStack not implemented")
}
func (UnimplementedEventStreamServiceServer) mustEmbedUnimplementedEventStreamServiceServer() {}
func (UnimplementedEventStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeEventStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamServiceServer will
// result in compilation errors.
type UnsafeEventStreamServiceServer interface {
	mustEmbedUnimplementedEventStreamServiceServer()
}

func RegisterEventStreamServiceServer(s grpc.ServiceRegistrar, srv EventStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedEventStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStreamService_ServiceDesc, srv)
}

func _EventStreamService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventStreamServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStreamService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _EventStreamService_ResolveStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveStackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStreamServiceServer).ResolveStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventStreamService_ResolveStack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStreamServiceServer).ResolveStack(ctx, req.(*ResolveStackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventStreamService_ServiceDesc is the grpc.ServiceDesc for EventStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ptop.v1.EventStreamService",
	HandlerType: (*EventStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveStack",
			Handler:    _EventStreamService_ResolveStack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EventStreamService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
