package symbol

import (
	"path"
	"strings"
)

// Canonicalization of the source paths the Go line table records.
//
// .gopclntab stores the path a file had on the BUILD machine, absolute unless
// the binary was built with -trimpath:
//
//	/home/ci/.local/share/mise/installs/go/1.26.5/src/runtime/sys_linux_arm64.s
//	/home/ci/go/pkg/mod/github.com/x/y@v1.2.3/pool.go
//
// Neither travels. Two hosts with Go installed in different places never
// produce the same file:line for the same code, so a consumer comparing
// signatures across machines finds nothing in common; and a consumer that
// persists what ptop sends ends up storing someone's home directory. Keying on
// the IMPORT PATH fixes both, and the symbol name already carries it (#107).

// goSourcePath rewrites a line-table path into one that means the same thing on
// another machine: the file's import path plus its basename.
//
//	runtime.futex               /…/go/1.26.5/src/runtime/sys_linux_arm64.s
//	                          → runtime/sys_linux_arm64.s
//	github.com/x/y.(*P).Do      /…/pkg/mod/github.com/x/y@v1.2.3/pool.go
//	                          → github.com/x/y/pool.go
//
// The rewrite is anchored: the directory has to END in the package path — or in
// as much of its tail as the checkout keeps, since a module cloned at
// /home/u/src/svc holds "internal/pool" but not "github.com/o/svc" — before the
// package path is put in its place. Some anchor is needed because gosym pairs
// the ENCLOSING function's name with the line table's file, and an inlined call
// makes the two disagree: the file is the callee's, the name the caller's.
// Requiring the directory to corroborate the name rejects the frames where they
// have plainly diverged. When nothing anchors, the basename alone goes out — it
// says less, but it says nothing false, and Func still carries the package.
//
// Idempotent, so a -trimpath binary (which already records the trimmed form)
// comes out unchanged.
func goSourcePath(fnName, file string) string {
	dir, base := path.Split(file)
	dir = strings.TrimSuffix(dir, "/")
	if base == "" {
		return file
	}
	if dir == "" {
		return file // "<autogenerated>" and friends — nothing to trim
	}

	if pkg := goPackageOf(fnName); pkg != "" && dirMatchesPkg(dir, pkg) {
		return pkg + "/" + base
	}
	// No anchor. Two markers still name a machine-independent root on their
	// own, so try them before giving up the directory entirely.
	if s, ok := afterMarker(file, "/pkg/mod/"); ok {
		return stripModuleVersions(s)
	}
	if s, ok := afterMarker(file, "/vendor/"); ok {
		return s
	}
	return base
}

// goPackageOf extracts the import path from a Go symbol name: everything before
// the first '.' that follows the last '/'.
//
//	runtime.futex                        → runtime
//	github.com/x/y/internal/p.(*P).Do    → github.com/x/y/internal/p
//	main.main                            → main
//
// Returns "" for a name with no package qualifier at all.
func goPackageOf(fnName string) string {
	tail := fnName
	if i := strings.LastIndexByte(fnName, '/'); i >= 0 {
		tail = fnName[i+1:]
	}
	dot := strings.IndexByte(tail, '.')
	if dot < 0 {
		return ""
	}
	return fnName[:len(fnName)-len(tail)+dot]
}

// dirMatchesPkg reports whether dir ends in pkg, comparing element by element
// from the right and ignoring the module cache's "@version" suffix. One
// matching element is enough, because the elements of dir above the match are
// exactly the machine-specific root this is trying to drop — a checkout of
// github.com/o/svc at /home/u/src/svc corroborates package
// github.com/o/svc/internal/pool with "internal/pool" and nothing more.
func dirMatchesPkg(dir, pkg string) bool {
	dirElems := strings.Split(dir, "/")
	pkgElems := strings.Split(pkg, "/")
	n := len(pkgElems)
	if len(dirElems) < n {
		n = len(dirElems)
	}
	for i := 1; i <= n; i++ {
		if trimModuleVersion(dirElems[len(dirElems)-i]) != pkgElems[len(pkgElems)-i] {
			return i > 1 // at least one element already agreed
		}
	}
	return n > 0
}

// afterMarker returns what follows the last occurrence of marker in s.
func afterMarker(s, marker string) (string, bool) {
	i := strings.LastIndex(s, marker)
	if i < 0 {
		return "", false
	}
	return s[i+len(marker):], true
}

// stripModuleVersions drops the "@v1.2.3" the module cache appends to a
// directory name, so a path keys on the module rather than on the version that
// happened to be built.
func stripModuleVersions(p string) string {
	if !strings.ContainsRune(p, '@') {
		return p
	}
	elems := strings.Split(p, "/")
	for i, e := range elems {
		elems[i] = trimModuleVersion(e)
	}
	return strings.Join(elems, "/")
}

func trimModuleVersion(elem string) string {
	if i := strings.IndexByte(elem, '@'); i >= 0 {
		return elem[:i]
	}
	return elem
}
