package symbol

import "testing"

func TestGoPackageOf(t *testing.T) {
	cases := []struct{ in, want string }{
		{"runtime.futex", "runtime"},
		{"main.main", "main"},
		{"internal/poll.(*FD).Read", "internal/poll"},
		{"github.com/x/y/internal/p.(*P).Do", "github.com/x/y/internal/p"},
		{"github.com/x/y.F[...]", "github.com/x/y"},
		{"sync.(*Mutex).Lock", "sync"},
		{"nopackage", ""},
		{"", ""},
	}
	for _, tc := range cases {
		if got := goPackageOf(tc.in); got != tc.want {
			t.Errorf("goPackageOf(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestGoSourcePath(t *testing.T) {
	cases := []struct {
		name, fn, file, want string
	}{
		{
			// The case that motivated #107: every futex in the process
			// resolved to this line, keyed by the build machine's GOROOT.
			"goroot absolute",
			"runtime.futex",
			"/home/ci/.local/share/mise/installs/go/1.26.5/src/runtime/sys_linux_arm64.s",
			"runtime/sys_linux_arm64.s",
		},
		{
			"goroot nested stdlib package",
			"internal/poll.(*FD).Read",
			"/usr/local/go/src/internal/poll/fd_unix.go",
			"internal/poll/fd_unix.go",
		},
		{
			"module cache carries its version",
			"github.com/x/y.(*P).Do",
			"/home/ci/go/pkg/mod/github.com/x/y@v1.2.3/pool.go",
			"github.com/x/y/pool.go",
		},
		{
			"vendored dependency",
			"github.com/x/y.(*P).Do",
			"/home/ci/src/svc/vendor/github.com/x/y/pool.go",
			"github.com/x/y/pool.go",
		},
		{
			// A checkout holds the package tail, never the module prefix.
			"main module checked out under any name",
			"github.com/o/svc/internal/pool.(*Pool).acquire",
			"/home/ci/src/svc/internal/pool/pool.go",
			"github.com/o/svc/internal/pool/pool.go",
		},
		{
			// -trimpath already records the canonical form: unchanged.
			"trimpath goroot is idempotent",
			"runtime.futex",
			"runtime/sys_linux_arm64.s",
			"runtime/sys_linux_arm64.s",
		},
		{
			"trimpath module cache is idempotent",
			"github.com/x/y.(*P).Do",
			"github.com/x/y@v1.2.3/pool.go",
			"github.com/x/y/pool.go",
		},
		{
			// package "main" sits in a directory named after anything at all,
			// so nothing anchors: the basename is all that can be said.
			"main package keeps only the basename",
			"main.main",
			"/home/ci/src/ordersvc/main.go",
			"main.go",
		},
		{
			// gosym names the enclosing func, so an inlined frame's file
			// belongs to another package. Better mute than mis-filed.
			"unanchored frame is not filed under the caller's package",
			"github.com/o/svc/api.Handle",
			"/home/ci/other/checkout/helper.go",
			"helper.go",
		},
		{
			"no directory to trim",
			"main.main",
			"<autogenerated>",
			"<autogenerated>",
		},
		{"empty file", "runtime.futex", "", ""},
		{"unqualified symbol", "sysenter", "/build/x/y.c", "y.c"},
	}
	for _, tc := range cases {
		if got := goSourcePath(tc.fn, tc.file); got != tc.want {
			t.Errorf("%s: goSourcePath(%q, %q) = %q, want %q", tc.name, tc.fn, tc.file, got, tc.want)
		}
	}
}

// The rewrite has to be a fixed point: a binary built with -trimpath already
// records what this produces, and a consumer keying on file:line must get the
// same key from both builds of the same source.
func TestGoSourcePathIdempotent(t *testing.T) {
	cases := [][2]string{
		{"runtime.futex", "/usr/lib/go/src/runtime/sys_linux_arm64.s"},
		{"github.com/x/y.(*P).Do", "/root/go/pkg/mod/github.com/x/y@v1.2.3/pool.go"},
		{"main.main", "/home/ci/src/ordersvc/main.go"},
		{"github.com/o/svc/internal/pool.(*Pool).acquire", "/home/ci/src/svc/internal/pool/pool.go"},
	}
	for _, tc := range cases {
		once := goSourcePath(tc[0], tc[1])
		if twice := goSourcePath(tc[0], once); twice != once {
			t.Errorf("goSourcePath(%q, ...) not idempotent: %q → %q", tc[0], once, twice)
		}
	}
}
