//go:build linux && ebpf

package bpf

import (
	_ "embed"
	"bytes"
	"errors"
	"fmt"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
)

// syscallsBPFObj is the BPF object compiled from programs/syscalls.bpf.c.
// Generated by `make gen` (clang -target bpf -c).
//
//go:embed programs/syscalls.bpf.o
var syscallsBPFObj []byte

// SyscallStat mirrors `struct syscall_stat` in syscalls.bpf.c.
// The layout must match the C struct byte-for-byte (8+8 bytes, no padding).
type SyscallStat struct {
	Count      uint64
	TotalLatNs uint64
}

// SyscallTracer loads the eBPF syscalls program, attaches it to the
// raw_syscalls/sys_{enter,exit} tracepoints, and exposes methods to read the
// counters map.
//
// Lifecycle:
//   t, err := OpenSyscallTracer(pid)
//   defer t.Close()                  // detaches programs + frees maps
//   stats, _ := t.Stats()            // snapshot of the syscall_count map
type SyscallTracer struct {
	coll        *ebpf.Collection
	enterLink   link.Link
	exitLink    link.Link
	syscallMap  *ebpf.Map
}

// OpenSyscallTracer opens the tracer for the target PID. Fails if the kernel
// doesn't support eBPF tracepoints, if capabilities are missing, or if the
// BPF object didn't pass kernel verification.
func OpenSyscallTracer(pid int) (*SyscallTracer, error) {
	if pid <= 0 {
		return nil, errors.New("invalid pid")
	}
	// Raises RLIMIT_MEMLOCK so the kernel accepts map allocations.
	// On 5.11+ kernels with BPF memcg this is a no-op but still safe.
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("rlimit.RemoveMemlock: %w", err)
	}

	spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(syscallsBPFObj))
	if err != nil {
		return nil, fmt.Errorf("parse BPF object: %w", err)
	}

	coll, err := ebpf.NewCollection(spec)
	if err != nil {
		return nil, fmt.Errorf("load BPF collection: %w", err)
	}

	t := &SyscallTracer{coll: coll}

	// Configure the target_pid map with the target PID (key=0 → val=pid).
	targetMap := coll.Maps["target_pid"]
	if targetMap == nil {
		t.Close()
		return nil, errors.New("target_pid map not found in BPF object")
	}
	var key uint32 = 0
	val := uint32(pid)
	if err := targetMap.Update(&key, &val, ebpf.UpdateAny); err != nil {
		t.Close()
		return nil, fmt.Errorf("set target_pid: %w", err)
	}

	t.syscallMap = coll.Maps["syscall_count"]
	if t.syscallMap == nil {
		t.Close()
		return nil, errors.New("syscall_count map not found")
	}

	enterProg := coll.Programs["handle_sys_enter"]
	exitProg := coll.Programs["handle_sys_exit"]
	if enterProg == nil || exitProg == nil {
		t.Close()
		return nil, errors.New("handle_sys_enter/exit programs not found")
	}

	// Attach to the tracepoints. This is what actually wires the program
	// into the kernel; up to here it was just loaded.
	enterLink, err := link.Tracepoint("raw_syscalls", "sys_enter", enterProg, nil)
	if err != nil {
		t.Close()
		return nil, fmt.Errorf("attach sys_enter: %w", err)
	}
	t.enterLink = enterLink

	exitLink, err := link.Tracepoint("raw_syscalls", "sys_exit", exitProg, nil)
	if err != nil {
		t.Close()
		return nil, fmt.Errorf("attach sys_exit: %w", err)
	}
	t.exitLink = exitLink

	return t, nil
}

// Stats returns a snapshot of the syscall_count map: syscall_id → {count, lat_total}.
// Iteration is safe even while the BPF program writes concurrently (it may
// skip or repeat marginal entries — acceptable for the UI).
func (t *SyscallTracer) Stats() (map[uint32]SyscallStat, error) {
	if t == nil || t.syscallMap == nil {
		return nil, errors.New("tracer not initialized")
	}
	out := make(map[uint32]SyscallStat, 64)
	var key uint32
	var val SyscallStat
	iter := t.syscallMap.Iterate()
	for iter.Next(&key, &val) {
		out[key] = val
	}
	if err := iter.Err(); err != nil {
		return out, err
	}
	return out, nil
}

// Close detaches the programs, frees maps and returns kernel resources.
// Idempotent; safe to call multiple times.
func (t *SyscallTracer) Close() error {
	if t == nil {
		return nil
	}
	var errs []error
	if t.enterLink != nil {
		if err := t.enterLink.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close sys_enter link: %w", err))
		}
		t.enterLink = nil
	}
	if t.exitLink != nil {
		if err := t.exitLink.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close sys_exit link: %w", err))
		}
		t.exitLink = nil
	}
	if t.coll != nil {
		t.coll.Close()
		t.coll = nil
		t.syscallMap = nil
	}
	return errors.Join(errs...)
}
